// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/correlation.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for replication mode
type ReplicationMode int32

const (
	ReplicationMode_CORRELATION_REPLICATION_MODE_INVALID ReplicationMode = 0
	ReplicationMode_CORRELATION_REPLICATION_MODE_LOCAL   ReplicationMode = 1
	ReplicationMode_CORRELATION_REPLICATION_MODE_GLOBAL  ReplicationMode = 2
)

// Enum value maps for ReplicationMode.
var (
	ReplicationMode_name = map[int32]string{
		0: "CORRELATION_REPLICATION_MODE_INVALID",
		1: "CORRELATION_REPLICATION_MODE_LOCAL",
		2: "CORRELATION_REPLICATION_MODE_GLOBAL",
	}
	ReplicationMode_value = map[string]int32{
		"CORRELATION_REPLICATION_MODE_INVALID": 0,
		"CORRELATION_REPLICATION_MODE_LOCAL":   1,
		"CORRELATION_REPLICATION_MODE_GLOBAL":  2,
	}
)

func (x ReplicationMode) Enum() *ReplicationMode {
	p := new(ReplicationMode)
	*p = x
	return p
}

func (x ReplicationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_components_correlation_proto_enumTypes[0].Descriptor()
}

func (ReplicationMode) Type() protoreflect.EnumType {
	return &file_components_correlation_proto_enumTypes[0]
}

func (x ReplicationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationMode.Descriptor instead.
func (ReplicationMode) EnumDescriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{0}
}

// Enum for correlation type
type CorrelationType int32

const (
	CorrelationType_CORRELATION_TYPE_INVALID   CorrelationType = 0
	CorrelationType_CORRELATION_TYPE_MANUAL    CorrelationType = 1
	CorrelationType_CORRELATION_TYPE_AUTOMATED CorrelationType = 2
)

// Enum value maps for CorrelationType.
var (
	CorrelationType_name = map[int32]string{
		0: "CORRELATION_TYPE_INVALID",
		1: "CORRELATION_TYPE_MANUAL",
		2: "CORRELATION_TYPE_AUTOMATED",
	}
	CorrelationType_value = map[string]int32{
		"CORRELATION_TYPE_INVALID":   0,
		"CORRELATION_TYPE_MANUAL":    1,
		"CORRELATION_TYPE_AUTOMATED": 2,
	}
)

func (x CorrelationType) Enum() *CorrelationType {
	p := new(CorrelationType)
	*p = x
	return p
}

func (x CorrelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CorrelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_correlation_proto_enumTypes[1].Descriptor()
}

func (CorrelationType) Type() protoreflect.EnumType {
	return &file_components_correlation_proto_enumTypes[1]
}

func (x CorrelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CorrelationType.Descriptor instead.
func (CorrelationType) EnumDescriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{1}
}

// Top-level Correlation type
type Correlation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primary       *Primary               `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary     *Secondary             `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Membership    *Membership            `protobuf:"bytes,3,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Correlation) Reset() {
	*x = Correlation{}
	mi := &file_components_correlation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Correlation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Correlation) ProtoMessage() {}

func (x *Correlation) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Correlation.ProtoReflect.Descriptor instead.
func (*Correlation) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{0}
}

func (x *Correlation) GetPrimary() *Primary {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *Correlation) GetSecondary() *Secondary {
	if x != nil {
		return x.Secondary
	}
	return nil
}

func (x *Correlation) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

// Primary type for Correlation
type Primary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SecondaryEntityIds []string               `protobuf:"bytes,1,rep,name=secondaryEntityIds,proto3" json:"secondaryEntityIds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Primary) Reset() {
	*x = Primary{}
	mi := &file_components_correlation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Primary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primary) ProtoMessage() {}

func (x *Primary) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primary.ProtoReflect.Descriptor instead.
func (*Primary) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{1}
}

func (x *Primary) GetSecondaryEntityIds() []string {
	if x != nil {
		return x.SecondaryEntityIds
	}
	return nil
}

// Secondary type for Correlation
type Secondary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrimaryEntityId string                 `protobuf:"bytes,1,opt,name=primaryEntityId,proto3" json:"primaryEntityId,omitempty"`
	Metadata        *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Secondary) Reset() {
	*x = Secondary{}
	mi := &file_components_correlation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secondary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secondary) ProtoMessage() {}

func (x *Secondary) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secondary.ProtoReflect.Descriptor instead.
func (*Secondary) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{2}
}

func (x *Secondary) GetPrimaryEntityId() string {
	if x != nil {
		return x.PrimaryEntityId
	}
	return ""
}

func (x *Secondary) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata structure
type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provenance      *Provenance            `protobuf:"bytes,1,opt,name=provenance,proto3" json:"provenance,omitempty"`
	ReplicationMode ReplicationMode        `protobuf:"varint,2,opt,name=replicationMode,proto3,enum=components.ReplicationMode" json:"replicationMode,omitempty"`
	Type            CorrelationType        `protobuf:"varint,3,opt,name=type,proto3,enum=components.CorrelationType" json:"type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_components_correlation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Metadata) GetReplicationMode() ReplicationMode {
	if x != nil {
		return x.ReplicationMode
	}
	return ReplicationMode_CORRELATION_REPLICATION_MODE_INVALID
}

func (x *Metadata) GetType() CorrelationType {
	if x != nil {
		return x.Type
	}
	return CorrelationType_CORRELATION_TYPE_INVALID
}

// Provenance is referenced but not defined in your Go code.
// Add definition or stub:
type Provenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_components_correlation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{4}
}

// Membership structure
type Membership struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CorrelationSetId string                 `protobuf:"bytes,1,opt,name=correlationSetId,proto3" json:"correlationSetId,omitempty"`
	Primary          *Primary               `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	NonPrimary       *Secondary             `protobuf:"bytes,3,opt,name=nonPrimary,proto3" json:"nonPrimary,omitempty"`
	Metadata         *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_components_correlation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{5}
}

func (x *Membership) GetCorrelationSetId() string {
	if x != nil {
		return x.CorrelationSetId
	}
	return ""
}

func (x *Membership) GetPrimary() *Primary {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *Membership) GetNonPrimary() *Secondary {
	if x != nil {
		return x.NonPrimary
	}
	return nil
}

func (x *Membership) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Decorrelation block
type Decorrelation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	All                  *All                   `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	DecorrelatedEntities []*DecorrelatedEntity  `protobuf:"bytes,2,rep,name=decorrelatedEntities,proto3" json:"decorrelatedEntities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Decorrelation) Reset() {
	*x = Decorrelation{}
	mi := &file_components_correlation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decorrelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decorrelation) ProtoMessage() {}

func (x *Decorrelation) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decorrelation.ProtoReflect.Descriptor instead.
func (*Decorrelation) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{6}
}

func (x *Decorrelation) GetAll() *All {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *Decorrelation) GetDecorrelatedEntities() []*DecorrelatedEntity {
	if x != nil {
		return x.DecorrelatedEntities
	}
	return nil
}

type All struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *All) Reset() {
	*x = All{}
	mi := &file_components_correlation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*All) ProtoMessage() {}

func (x *All) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use All.ProtoReflect.Descriptor instead.
func (*All) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{7}
}

func (x *All) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DecorrelatedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecorrelatedEntity) Reset() {
	*x = DecorrelatedEntity{}
	mi := &file_components_correlation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecorrelatedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecorrelatedEntity) ProtoMessage() {}

func (x *DecorrelatedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_components_correlation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecorrelatedEntity.ProtoReflect.Descriptor instead.
func (*DecorrelatedEntity) Descriptor() ([]byte, []int) {
	return file_components_correlation_proto_rawDescGZIP(), []int{8}
}

func (x *DecorrelatedEntity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DecorrelatedEntity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_components_correlation_proto protoreflect.FileDescriptor

const file_components_correlation_proto_rawDesc = "" +
	"\n" +
	"\x1ccomponents/correlation.proto\x12\n" +
	"components\"\xa9\x01\n" +
	"\vCorrelation\x12-\n" +
	"\aprimary\x18\x01 \x01(\v2\x13.components.PrimaryR\aprimary\x123\n" +
	"\tsecondary\x18\x02 \x01(\v2\x15.components.SecondaryR\tsecondary\x126\n" +
	"\n" +
	"membership\x18\x03 \x01(\v2\x16.components.MembershipR\n" +
	"membership\"9\n" +
	"\aPrimary\x12.\n" +
	"\x12secondaryEntityIds\x18\x01 \x03(\tR\x12secondaryEntityIds\"g\n" +
	"\tSecondary\x12(\n" +
	"\x0fprimaryEntityId\x18\x01 \x01(\tR\x0fprimaryEntityId\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.components.MetadataR\bmetadata\"\xba\x01\n" +
	"\bMetadata\x126\n" +
	"\n" +
	"provenance\x18\x01 \x01(\v2\x16.components.ProvenanceR\n" +
	"provenance\x12E\n" +
	"\x0freplicationMode\x18\x02 \x01(\x0e2\x1b.components.ReplicationModeR\x0freplicationMode\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.components.CorrelationTypeR\x04type\"\f\n" +
	"\n" +
	"Provenance\"\xd0\x01\n" +
	"\n" +
	"Membership\x12*\n" +
	"\x10correlationSetId\x18\x01 \x01(\tR\x10correlationSetId\x12-\n" +
	"\aprimary\x18\x02 \x01(\v2\x13.components.PrimaryR\aprimary\x125\n" +
	"\n" +
	"nonPrimary\x18\x03 \x01(\v2\x15.components.SecondaryR\n" +
	"nonPrimary\x120\n" +
	"\bmetadata\x18\x04 \x01(\v2\x14.components.MetadataR\bmetadata\"\x86\x01\n" +
	"\rDecorrelation\x12!\n" +
	"\x03all\x18\x01 \x01(\v2\x0f.components.AllR\x03all\x12R\n" +
	"\x14decorrelatedEntities\x18\x02 \x03(\v2\x1e.components.DecorrelatedEntityR\x14decorrelatedEntities\"7\n" +
	"\x03All\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.components.MetadataR\bmetadata\"b\n" +
	"\x12DecorrelatedEntity\x12\x1a\n" +
	"\bentityId\x18\x01 \x01(\tR\bentityId\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.components.MetadataR\bmetadata*\x8c\x01\n" +
	"\x0fReplicationMode\x12(\n" +
	"$CORRELATION_REPLICATION_MODE_INVALID\x10\x00\x12&\n" +
	"\"CORRELATION_REPLICATION_MODE_LOCAL\x10\x01\x12'\n" +
	"#CORRELATION_REPLICATION_MODE_GLOBAL\x10\x02*l\n" +
	"\x0fCorrelationType\x12\x1c\n" +
	"\x18CORRELATION_TYPE_INVALID\x10\x00\x12\x1b\n" +
	"\x17CORRELATION_TYPE_MANUAL\x10\x01\x12\x1e\n" +
	"\x1aCORRELATION_TYPE_AUTOMATED\x10\x02B\rZ\v/componentsb\x06proto3"

var (
	file_components_correlation_proto_rawDescOnce sync.Once
	file_components_correlation_proto_rawDescData []byte
)

func file_components_correlation_proto_rawDescGZIP() []byte {
	file_components_correlation_proto_rawDescOnce.Do(func() {
		file_components_correlation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_correlation_proto_rawDesc), len(file_components_correlation_proto_rawDesc)))
	})
	return file_components_correlation_proto_rawDescData
}

var file_components_correlation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_components_correlation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_components_correlation_proto_goTypes = []any{
	(ReplicationMode)(0),       // 0: components.ReplicationMode
	(CorrelationType)(0),       // 1: components.CorrelationType
	(*Correlation)(nil),        // 2: components.Correlation
	(*Primary)(nil),            // 3: components.Primary
	(*Secondary)(nil),          // 4: components.Secondary
	(*Metadata)(nil),           // 5: components.Metadata
	(*Provenance)(nil),         // 6: components.Provenance
	(*Membership)(nil),         // 7: components.Membership
	(*Decorrelation)(nil),      // 8: components.Decorrelation
	(*All)(nil),                // 9: components.All
	(*DecorrelatedEntity)(nil), // 10: components.DecorrelatedEntity
}
var file_components_correlation_proto_depIdxs = []int32{
	3,  // 0: components.Correlation.primary:type_name -> components.Primary
	4,  // 1: components.Correlation.secondary:type_name -> components.Secondary
	7,  // 2: components.Correlation.membership:type_name -> components.Membership
	5,  // 3: components.Secondary.metadata:type_name -> components.Metadata
	6,  // 4: components.Metadata.provenance:type_name -> components.Provenance
	0,  // 5: components.Metadata.replicationMode:type_name -> components.ReplicationMode
	1,  // 6: components.Metadata.type:type_name -> components.CorrelationType
	3,  // 7: components.Membership.primary:type_name -> components.Primary
	4,  // 8: components.Membership.nonPrimary:type_name -> components.Secondary
	5,  // 9: components.Membership.metadata:type_name -> components.Metadata
	9,  // 10: components.Decorrelation.all:type_name -> components.All
	10, // 11: components.Decorrelation.decorrelatedEntities:type_name -> components.DecorrelatedEntity
	5,  // 12: components.All.metadata:type_name -> components.Metadata
	5,  // 13: components.DecorrelatedEntity.metadata:type_name -> components.Metadata
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_components_correlation_proto_init() }
func file_components_correlation_proto_init() {
	if File_components_correlation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_correlation_proto_rawDesc), len(file_components_correlation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_correlation_proto_goTypes,
		DependencyIndexes: file_components_correlation_proto_depIdxs,
		EnumInfos:         file_components_correlation_proto_enumTypes,
		MessageInfos:      file_components_correlation_proto_msgTypes,
	}.Build()
	File_components_correlation_proto = out.File
	file_components_correlation_proto_goTypes = nil
	file_components_correlation_proto_depIdxs = nil
}
