// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: geo_details.proto

package Lattice_SDK_Secure_Sword_git

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoType int32

const (
	GeoType_GEO_TYPE_INVALID         GeoType = 0
	GeoType_GEO_TYPE_GENERAL         GeoType = 1
	GeoType_GEO_TYPE_HAZARD          GeoType = 2
	GeoType_GEO_TYPE_EMERGENCY       GeoType = 3
	GeoType_GEO_TYPE_ENGAGEMENT_ZONE GeoType = 4
	GeoType_GEO_TYPE_CONTROL_AREA    GeoType = 5
	GeoType_GEO_TYPE_BULLSEYE        GeoType = 6
	GeoType_GEO_TYPE_ACM             GeoType = 7
)

// Enum value maps for GeoType.
var (
	GeoType_name = map[int32]string{
		0: "GEO_TYPE_INVALID",
		1: "GEO_TYPE_GENERAL",
		2: "GEO_TYPE_HAZARD",
		3: "GEO_TYPE_EMERGENCY",
		4: "GEO_TYPE_ENGAGEMENT_ZONE",
		5: "GEO_TYPE_CONTROL_AREA",
		6: "GEO_TYPE_BULLSEYE",
		7: "GEO_TYPE_ACM",
	}
	GeoType_value = map[string]int32{
		"GEO_TYPE_INVALID":         0,
		"GEO_TYPE_GENERAL":         1,
		"GEO_TYPE_HAZARD":          2,
		"GEO_TYPE_EMERGENCY":       3,
		"GEO_TYPE_ENGAGEMENT_ZONE": 4,
		"GEO_TYPE_CONTROL_AREA":    5,
		"GEO_TYPE_BULLSEYE":        6,
		"GEO_TYPE_ACM":             7,
	}
)

func (x GeoType) Enum() *GeoType {
	p := new(GeoType)
	*p = x
	return p
}

func (x GeoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeoType) Descriptor() protoreflect.EnumDescriptor {
	return file_geo_details_proto_enumTypes[0].Descriptor()
}

func (GeoType) Type() protoreflect.EnumType {
	return &file_geo_details_proto_enumTypes[0]
}

func (x GeoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeoType.Descriptor instead.
func (GeoType) EnumDescriptor() ([]byte, []int) {
	return file_geo_details_proto_rawDescGZIP(), []int{0}
}

type ControlAreaType int32

const (
	ControlAreaType_CONTROL_AREA_TYPE_INVALID       ControlAreaType = 0
	ControlAreaType_CONTROL_AREA_TYPE_KEEP_IN_ZONE  ControlAreaType = 1
	ControlAreaType_CONTROL_AREA_TYPE_KEEP_OUT_ZONE ControlAreaType = 2
	ControlAreaType_CONTROL_AREA_TYPE_DITCH_ZONE    ControlAreaType = 3
	ControlAreaType_CONTROL_AREA_TYPE_LOITER_ZONE   ControlAreaType = 4
)

// Enum value maps for ControlAreaType.
var (
	ControlAreaType_name = map[int32]string{
		0: "CONTROL_AREA_TYPE_INVALID",
		1: "CONTROL_AREA_TYPE_KEEP_IN_ZONE",
		2: "CONTROL_AREA_TYPE_KEEP_OUT_ZONE",
		3: "CONTROL_AREA_TYPE_DITCH_ZONE",
		4: "CONTROL_AREA_TYPE_LOITER_ZONE",
	}
	ControlAreaType_value = map[string]int32{
		"CONTROL_AREA_TYPE_INVALID":       0,
		"CONTROL_AREA_TYPE_KEEP_IN_ZONE":  1,
		"CONTROL_AREA_TYPE_KEEP_OUT_ZONE": 2,
		"CONTROL_AREA_TYPE_DITCH_ZONE":    3,
		"CONTROL_AREA_TYPE_LOITER_ZONE":   4,
	}
)

func (x ControlAreaType) Enum() *ControlAreaType {
	p := new(ControlAreaType)
	*p = x
	return p
}

func (x ControlAreaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlAreaType) Descriptor() protoreflect.EnumDescriptor {
	return file_geo_details_proto_enumTypes[1].Descriptor()
}

func (ControlAreaType) Type() protoreflect.EnumType {
	return &file_geo_details_proto_enumTypes[1]
}

func (x ControlAreaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlAreaType.Descriptor instead.
func (ControlAreaType) EnumDescriptor() ([]byte, []int) {
	return file_geo_details_proto_rawDescGZIP(), []int{1}
}

type AcmType int32

const (
	AcmType_ACM_DETAIL_TYPE_INVALID      AcmType = 0
	AcmType_ACM_DETAIL_TYPE_LANDING_ZONE AcmType = 1
)

// Enum value maps for AcmType.
var (
	AcmType_name = map[int32]string{
		0: "ACM_DETAIL_TYPE_INVALID",
		1: "ACM_DETAIL_TYPE_LANDING_ZONE",
	}
	AcmType_value = map[string]int32{
		"ACM_DETAIL_TYPE_INVALID":      0,
		"ACM_DETAIL_TYPE_LANDING_ZONE": 1,
	}
)

func (x AcmType) Enum() *AcmType {
	p := new(AcmType)
	*p = x
	return p
}

func (x AcmType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcmType) Descriptor() protoreflect.EnumDescriptor {
	return file_geo_details_proto_enumTypes[2].Descriptor()
}

func (AcmType) Type() protoreflect.EnumType {
	return &file_geo_details_proto_enumTypes[2]
}

func (x AcmType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcmType.Descriptor instead.
func (AcmType) EnumDescriptor() ([]byte, []int) {
	return file_geo_details_proto_rawDescGZIP(), []int{2}
}

type ControlArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlAreaType        `protobuf:"varint,1,opt,name=type,proto3,enum=components.ControlAreaType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlArea) Reset() {
	*x = ControlArea{}
	mi := &file_geo_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlArea) ProtoMessage() {}

func (x *ControlArea) ProtoReflect() protoreflect.Message {
	mi := &file_geo_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlArea.ProtoReflect.Descriptor instead.
func (*ControlArea) Descriptor() ([]byte, []int) {
	return file_geo_details_proto_rawDescGZIP(), []int{0}
}

func (x *ControlArea) GetType() ControlAreaType {
	if x != nil {
		return x.Type
	}
	return ControlAreaType_CONTROL_AREA_TYPE_INVALID
}

type Acm struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcmType        AcmType                `protobuf:"varint,1,opt,name=acm_type,json=acmType,proto3,enum=components.AcmType" json:"acm_type,omitempty"`
	AcmDescription string                 `protobuf:"bytes,2,opt,name=acm_description,json=acmDescription,proto3" json:"acm_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Acm) Reset() {
	*x = Acm{}
	mi := &file_geo_details_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acm) ProtoMessage() {}

func (x *Acm) ProtoReflect() protoreflect.Message {
	mi := &file_geo_details_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acm.ProtoReflect.Descriptor instead.
func (*Acm) Descriptor() ([]byte, []int) {
	return file_geo_details_proto_rawDescGZIP(), []int{1}
}

func (x *Acm) GetAcmType() AcmType {
	if x != nil {
		return x.AcmType
	}
	return AcmType_ACM_DETAIL_TYPE_INVALID
}

func (x *Acm) GetAcmDescription() string {
	if x != nil {
		return x.AcmDescription
	}
	return ""
}

type GeoDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GeoType                `protobuf:"varint,1,opt,name=type,proto3,enum=components.GeoType" json:"type,omitempty"`
	ControlArea   *ControlArea           `protobuf:"bytes,2,opt,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"`
	Acm           *Acm                   `protobuf:"bytes,3,opt,name=acm,proto3" json:"acm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoDetails) Reset() {
	*x = GeoDetails{}
	mi := &file_geo_details_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoDetails) ProtoMessage() {}

func (x *GeoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_geo_details_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoDetails.ProtoReflect.Descriptor instead.
func (*GeoDetails) Descriptor() ([]byte, []int) {
	return file_geo_details_proto_rawDescGZIP(), []int{2}
}

func (x *GeoDetails) GetType() GeoType {
	if x != nil {
		return x.Type
	}
	return GeoType_GEO_TYPE_INVALID
}

func (x *GeoDetails) GetControlArea() *ControlArea {
	if x != nil {
		return x.ControlArea
	}
	return nil
}

func (x *GeoDetails) GetAcm() *Acm {
	if x != nil {
		return x.Acm
	}
	return nil
}

var File_geo_details_proto protoreflect.FileDescriptor

const file_geo_details_proto_rawDesc = "" +
	"\n" +
	"\x11geo_details.proto\x12\n" +
	"components\">\n" +
	"\vControlArea\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.components.ControlAreaTypeR\x04type\"^\n" +
	"\x03Acm\x12.\n" +
	"\bacm_type\x18\x01 \x01(\x0e2\x13.components.AcmTypeR\aacmType\x12'\n" +
	"\x0facm_description\x18\x02 \x01(\tR\x0eacmDescription\"\x94\x01\n" +
	"\n" +
	"GeoDetails\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.components.GeoTypeR\x04type\x12:\n" +
	"\fcontrol_area\x18\x02 \x01(\v2\x17.components.ControlAreaR\vcontrolArea\x12!\n" +
	"\x03acm\x18\x03 \x01(\v2\x0f.components.AcmR\x03acm*\xc4\x01\n" +
	"\aGeoType\x12\x14\n" +
	"\x10GEO_TYPE_INVALID\x10\x00\x12\x14\n" +
	"\x10GEO_TYPE_GENERAL\x10\x01\x12\x13\n" +
	"\x0fGEO_TYPE_HAZARD\x10\x02\x12\x16\n" +
	"\x12GEO_TYPE_EMERGENCY\x10\x03\x12\x1c\n" +
	"\x18GEO_TYPE_ENGAGEMENT_ZONE\x10\x04\x12\x19\n" +
	"\x15GEO_TYPE_CONTROL_AREA\x10\x05\x12\x15\n" +
	"\x11GEO_TYPE_BULLSEYE\x10\x06\x12\x10\n" +
	"\fGEO_TYPE_ACM\x10\a*\xbe\x01\n" +
	"\x0fControlAreaType\x12\x1d\n" +
	"\x19CONTROL_AREA_TYPE_INVALID\x10\x00\x12\"\n" +
	"\x1eCONTROL_AREA_TYPE_KEEP_IN_ZONE\x10\x01\x12#\n" +
	"\x1fCONTROL_AREA_TYPE_KEEP_OUT_ZONE\x10\x02\x12 \n" +
	"\x1cCONTROL_AREA_TYPE_DITCH_ZONE\x10\x03\x12!\n" +
	"\x1dCONTROL_AREA_TYPE_LOITER_ZONE\x10\x04*H\n" +
	"\aAcmType\x12\x1b\n" +
	"\x17ACM_DETAIL_TYPE_INVALID\x10\x00\x12 \n" +
	"\x1cACM_DETAIL_TYPE_LANDING_ZONE\x10\x01B8Z6github.com/nickbassirpour/Lattice_SDK_Secure_Sword.gitb\x06proto3"

var (
	file_geo_details_proto_rawDescOnce sync.Once
	file_geo_details_proto_rawDescData []byte
)

func file_geo_details_proto_rawDescGZIP() []byte {
	file_geo_details_proto_rawDescOnce.Do(func() {
		file_geo_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_details_proto_rawDesc), len(file_geo_details_proto_rawDesc)))
	})
	return file_geo_details_proto_rawDescData
}

var file_geo_details_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_geo_details_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_geo_details_proto_goTypes = []any{
	(GeoType)(0),         // 0: components.GeoType
	(ControlAreaType)(0), // 1: components.ControlAreaType
	(AcmType)(0),         // 2: components.AcmType
	(*ControlArea)(nil),  // 3: components.ControlArea
	(*Acm)(nil),          // 4: components.Acm
	(*GeoDetails)(nil),   // 5: components.GeoDetails
}
var file_geo_details_proto_depIdxs = []int32{
	1, // 0: components.ControlArea.type:type_name -> components.ControlAreaType
	2, // 1: components.Acm.acm_type:type_name -> components.AcmType
	0, // 2: components.GeoDetails.type:type_name -> components.GeoType
	3, // 3: components.GeoDetails.control_area:type_name -> components.ControlArea
	4, // 4: components.GeoDetails.acm:type_name -> components.Acm
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_geo_details_proto_init() }
func file_geo_details_proto_init() {
	if File_geo_details_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_details_proto_rawDesc), len(file_geo_details_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geo_details_proto_goTypes,
		DependencyIndexes: file_geo_details_proto_depIdxs,
		EnumInfos:         file_geo_details_proto_enumTypes,
		MessageInfos:      file_geo_details_proto_msgTypes,
	}.Build()
	File_geo_details_proto = out.File
	file_geo_details_proto_goTypes = nil
	file_geo_details_proto_depIdxs = nil
}
