// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/geoshape.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Line          *Line                  `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Polygon       *Polygon               `protobuf:"bytes,3,opt,name=polygon,proto3" json:"polygon,omitempty"`
	Ellipse       *Ellipse               `protobuf:"bytes,4,opt,name=ellipse,proto3" json:"ellipse,omitempty"`
	Ellipsoid     *Ellipsoid             `protobuf:"bytes,5,opt,name=ellipsoid,proto3" json:"ellipsoid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoShape) Reset() {
	*x = GeoShape{}
	mi := &file_components_geoshape_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoShape) ProtoMessage() {}

func (x *GeoShape) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoShape.ProtoReflect.Descriptor instead.
func (*GeoShape) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{0}
}

func (x *GeoShape) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *GeoShape) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *GeoShape) GetPolygon() *Polygon {
	if x != nil {
		return x.Polygon
	}
	return nil
}

func (x *GeoShape) GetEllipse() *Ellipse {
	if x != nil {
		return x.Ellipse
	}
	return nil
}

func (x *GeoShape) GetEllipsoid() *Ellipsoid {
	if x != nil {
		return x.Ellipsoid
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_components_geoshape_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_components_geoshape_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{2}
}

func (x *Line) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rings         []*Ring                `protobuf:"bytes,1,rep,name=rings,proto3" json:"rings,omitempty"`
	IsRectangle   bool                   `protobuf:"varint,2,opt,name=isRectangle,proto3" json:"isRectangle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_components_geoshape_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{3}
}

func (x *Polygon) GetRings() []*Ring {
	if x != nil {
		return x.Rings
	}
	return nil
}

func (x *Polygon) GetIsRectangle() bool {
	if x != nil {
		return x.IsRectangle
	}
	return false
}

type Ring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*LinearRing          `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ring) Reset() {
	*x = Ring{}
	mi := &file_components_geoshape_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ring) ProtoMessage() {}

func (x *Ring) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ring.ProtoReflect.Descriptor instead.
func (*Ring) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{4}
}

func (x *Ring) GetPositions() []*LinearRing {
	if x != nil {
		return x.Positions
	}
	return nil
}

type LinearRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	HeightM       float32                `protobuf:"fixed32,2,opt,name=heightM,proto3" json:"heightM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinearRing) Reset() {
	*x = LinearRing{}
	mi := &file_components_geoshape_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearRing) ProtoMessage() {}

func (x *LinearRing) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearRing.ProtoReflect.Descriptor instead.
func (*LinearRing) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{5}
}

func (x *LinearRing) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *LinearRing) GetHeightM() float32 {
	if x != nil {
		return x.HeightM
	}
	return 0
}

type Ellipse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SemiMajorAxisM float64                `protobuf:"fixed64,1,opt,name=semiMajorAxisM,proto3" json:"semiMajorAxisM,omitempty"`
	SemiMinorAxisM float64                `protobuf:"fixed64,2,opt,name=semiMinorAxisM,proto3" json:"semiMinorAxisM,omitempty"`
	OrientationD   float64                `protobuf:"fixed64,3,opt,name=orientationD,proto3" json:"orientationD,omitempty"`
	HeightM        float64                `protobuf:"fixed64,4,opt,name=heightM,proto3" json:"heightM,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Ellipse) Reset() {
	*x = Ellipse{}
	mi := &file_components_geoshape_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ellipse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ellipse) ProtoMessage() {}

func (x *Ellipse) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ellipse.ProtoReflect.Descriptor instead.
func (*Ellipse) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{6}
}

func (x *Ellipse) GetSemiMajorAxisM() float64 {
	if x != nil {
		return x.SemiMajorAxisM
	}
	return 0
}

func (x *Ellipse) GetSemiMinorAxisM() float64 {
	if x != nil {
		return x.SemiMinorAxisM
	}
	return 0
}

func (x *Ellipse) GetOrientationD() float64 {
	if x != nil {
		return x.OrientationD
	}
	return 0
}

func (x *Ellipse) GetHeightM() float64 {
	if x != nil {
		return x.HeightM
	}
	return 0
}

type Ellipsoid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForwardAxisM  float64                `protobuf:"fixed64,1,opt,name=forwardAxisM,proto3" json:"forwardAxisM,omitempty"`
	SideAxisM     float64                `protobuf:"fixed64,2,opt,name=sideAxisM,proto3" json:"sideAxisM,omitempty"`
	UpAxisM       float64                `protobuf:"fixed64,3,opt,name=upAxisM,proto3" json:"upAxisM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ellipsoid) Reset() {
	*x = Ellipsoid{}
	mi := &file_components_geoshape_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ellipsoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ellipsoid) ProtoMessage() {}

func (x *Ellipsoid) ProtoReflect() protoreflect.Message {
	mi := &file_components_geoshape_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ellipsoid.ProtoReflect.Descriptor instead.
func (*Ellipsoid) Descriptor() ([]byte, []int) {
	return file_components_geoshape_proto_rawDescGZIP(), []int{7}
}

func (x *Ellipsoid) GetForwardAxisM() float64 {
	if x != nil {
		return x.ForwardAxisM
	}
	return 0
}

func (x *Ellipsoid) GetSideAxisM() float64 {
	if x != nil {
		return x.SideAxisM
	}
	return 0
}

func (x *Ellipsoid) GetUpAxisM() float64 {
	if x != nil {
		return x.UpAxisM
	}
	return 0
}

var File_components_geoshape_proto protoreflect.FileDescriptor

const file_components_geoshape_proto_rawDesc = "" +
	"\n" +
	"\x19components/geoshape.proto\x12\n" +
	"components\x1a\x19components/position.proto\"\xec\x01\n" +
	"\bGeoShape\x12'\n" +
	"\x05point\x18\x01 \x01(\v2\x11.components.PointR\x05point\x12$\n" +
	"\x04line\x18\x02 \x01(\v2\x10.components.LineR\x04line\x12-\n" +
	"\apolygon\x18\x03 \x01(\v2\x13.components.PolygonR\apolygon\x12-\n" +
	"\aellipse\x18\x04 \x01(\v2\x13.components.EllipseR\aellipse\x123\n" +
	"\tellipsoid\x18\x05 \x01(\v2\x15.components.EllipsoidR\tellipsoid\"9\n" +
	"\x05Point\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.components.PositionR\bposition\"8\n" +
	"\x04Line\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.components.PositionR\bposition\"S\n" +
	"\aPolygon\x12&\n" +
	"\x05rings\x18\x01 \x03(\v2\x10.components.RingR\x05rings\x12 \n" +
	"\visRectangle\x18\x02 \x01(\bR\visRectangle\"<\n" +
	"\x04Ring\x124\n" +
	"\tpositions\x18\x01 \x03(\v2\x16.components.LinearRingR\tpositions\"X\n" +
	"\n" +
	"LinearRing\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.components.PositionR\bposition\x12\x18\n" +
	"\aheightM\x18\x02 \x01(\x02R\aheightM\"\x97\x01\n" +
	"\aEllipse\x12&\n" +
	"\x0esemiMajorAxisM\x18\x01 \x01(\x01R\x0esemiMajorAxisM\x12&\n" +
	"\x0esemiMinorAxisM\x18\x02 \x01(\x01R\x0esemiMinorAxisM\x12\"\n" +
	"\forientationD\x18\x03 \x01(\x01R\forientationD\x12\x18\n" +
	"\aheightM\x18\x04 \x01(\x01R\aheightM\"g\n" +
	"\tEllipsoid\x12\"\n" +
	"\fforwardAxisM\x18\x01 \x01(\x01R\fforwardAxisM\x12\x1c\n" +
	"\tsideAxisM\x18\x02 \x01(\x01R\tsideAxisM\x12\x18\n" +
	"\aupAxisM\x18\x03 \x01(\x01R\aupAxisMB\rZ\v/componentsb\x06proto3"

var (
	file_components_geoshape_proto_rawDescOnce sync.Once
	file_components_geoshape_proto_rawDescData []byte
)

func file_components_geoshape_proto_rawDescGZIP() []byte {
	file_components_geoshape_proto_rawDescOnce.Do(func() {
		file_components_geoshape_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_geoshape_proto_rawDesc), len(file_components_geoshape_proto_rawDesc)))
	})
	return file_components_geoshape_proto_rawDescData
}

var file_components_geoshape_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_components_geoshape_proto_goTypes = []any{
	(*GeoShape)(nil),   // 0: components.GeoShape
	(*Point)(nil),      // 1: components.Point
	(*Line)(nil),       // 2: components.Line
	(*Polygon)(nil),    // 3: components.Polygon
	(*Ring)(nil),       // 4: components.Ring
	(*LinearRing)(nil), // 5: components.LinearRing
	(*Ellipse)(nil),    // 6: components.Ellipse
	(*Ellipsoid)(nil),  // 7: components.Ellipsoid
	(*Position)(nil),   // 8: components.Position
}
var file_components_geoshape_proto_depIdxs = []int32{
	1,  // 0: components.GeoShape.point:type_name -> components.Point
	2,  // 1: components.GeoShape.line:type_name -> components.Line
	3,  // 2: components.GeoShape.polygon:type_name -> components.Polygon
	6,  // 3: components.GeoShape.ellipse:type_name -> components.Ellipse
	7,  // 4: components.GeoShape.ellipsoid:type_name -> components.Ellipsoid
	8,  // 5: components.Point.position:type_name -> components.Position
	8,  // 6: components.Line.position:type_name -> components.Position
	4,  // 7: components.Polygon.rings:type_name -> components.Ring
	5,  // 8: components.Ring.positions:type_name -> components.LinearRing
	8,  // 9: components.LinearRing.position:type_name -> components.Position
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_components_geoshape_proto_init() }
func file_components_geoshape_proto_init() {
	if File_components_geoshape_proto != nil {
		return
	}
	file_components_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_geoshape_proto_rawDesc), len(file_components_geoshape_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_geoshape_proto_goTypes,
		DependencyIndexes: file_components_geoshape_proto_depIdxs,
		MessageInfos:      file_components_geoshape_proto_msgTypes,
	}.Build()
	File_components_geoshape_proto = out.File
	file_components_geoshape_proto_goTypes = nil
	file_components_geoshape_proto_depIdxs = nil
}
