// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/groupdetails.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArmyEchelon int32

const (
	ArmyEchelon_ARMY_ECHELON_INVALID   ArmyEchelon = 0
	ArmyEchelon_ARMY_ECHELON_FIRE_TEAM ArmyEchelon = 1
	ArmyEchelon_ARMY_ECHELON_SQUAD     ArmyEchelon = 2
	ArmyEchelon_ARMY_ECHELON_PLATOON   ArmyEchelon = 3
	ArmyEchelon_ARMY_ECHELON_COMPANY   ArmyEchelon = 4
	ArmyEchelon_ARMY_ECHELON_BATTALION ArmyEchelon = 5
	ArmyEchelon_ARMY_ECHELON_REGIMENT  ArmyEchelon = 6
	ArmyEchelon_ARMY_ECHELON_BRIGADE   ArmyEchelon = 7
	ArmyEchelon_ARMY_ECHELON_DIVISION  ArmyEchelon = 8
	ArmyEchelon_ARMY_ECHELON_CORPS     ArmyEchelon = 9
	ArmyEchelon_ARMY_ECHELON_ARMY      ArmyEchelon = 10
)

// Enum value maps for ArmyEchelon.
var (
	ArmyEchelon_name = map[int32]string{
		0:  "ARMY_ECHELON_INVALID",
		1:  "ARMY_ECHELON_FIRE_TEAM",
		2:  "ARMY_ECHELON_SQUAD",
		3:  "ARMY_ECHELON_PLATOON",
		4:  "ARMY_ECHELON_COMPANY",
		5:  "ARMY_ECHELON_BATTALION",
		6:  "ARMY_ECHELON_REGIMENT",
		7:  "ARMY_ECHELON_BRIGADE",
		8:  "ARMY_ECHELON_DIVISION",
		9:  "ARMY_ECHELON_CORPS",
		10: "ARMY_ECHELON_ARMY",
	}
	ArmyEchelon_value = map[string]int32{
		"ARMY_ECHELON_INVALID":   0,
		"ARMY_ECHELON_FIRE_TEAM": 1,
		"ARMY_ECHELON_SQUAD":     2,
		"ARMY_ECHELON_PLATOON":   3,
		"ARMY_ECHELON_COMPANY":   4,
		"ARMY_ECHELON_BATTALION": 5,
		"ARMY_ECHELON_REGIMENT":  6,
		"ARMY_ECHELON_BRIGADE":   7,
		"ARMY_ECHELON_DIVISION":  8,
		"ARMY_ECHELON_CORPS":     9,
		"ARMY_ECHELON_ARMY":      10,
	}
)

func (x ArmyEchelon) Enum() *ArmyEchelon {
	p := new(ArmyEchelon)
	*p = x
	return p
}

func (x ArmyEchelon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArmyEchelon) Descriptor() protoreflect.EnumDescriptor {
	return file_components_groupdetails_proto_enumTypes[0].Descriptor()
}

func (ArmyEchelon) Type() protoreflect.EnumType {
	return &file_components_groupdetails_proto_enumTypes[0]
}

func (x ArmyEchelon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArmyEchelon.Descriptor instead.
func (ArmyEchelon) EnumDescriptor() ([]byte, []int) {
	return file_components_groupdetails_proto_rawDescGZIP(), []int{0}
}

type GroupDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Echelon       *Echelon               `protobuf:"bytes,2,opt,name=echelon,proto3" json:"echelon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDetails) Reset() {
	*x = GroupDetails{}
	mi := &file_components_groupdetails_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetails) ProtoMessage() {}

func (x *GroupDetails) ProtoReflect() protoreflect.Message {
	mi := &file_components_groupdetails_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetails.ProtoReflect.Descriptor instead.
func (*GroupDetails) Descriptor() ([]byte, []int) {
	return file_components_groupdetails_proto_rawDescGZIP(), []int{0}
}

func (x *GroupDetails) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *GroupDetails) GetEchelon() *Echelon {
	if x != nil {
		return x.Echelon
	}
	return nil
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_components_groupdetails_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_components_groupdetails_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_components_groupdetails_proto_rawDescGZIP(), []int{1}
}

type Echelon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArmyEchelon   ArmyEchelon            `protobuf:"varint,1,opt,name=armyEchelon,proto3,enum=components.ArmyEchelon" json:"armyEchelon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echelon) Reset() {
	*x = Echelon{}
	mi := &file_components_groupdetails_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echelon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echelon) ProtoMessage() {}

func (x *Echelon) ProtoReflect() protoreflect.Message {
	mi := &file_components_groupdetails_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echelon.ProtoReflect.Descriptor instead.
func (*Echelon) Descriptor() ([]byte, []int) {
	return file_components_groupdetails_proto_rawDescGZIP(), []int{2}
}

func (x *Echelon) GetArmyEchelon() ArmyEchelon {
	if x != nil {
		return x.ArmyEchelon
	}
	return ArmyEchelon_ARMY_ECHELON_INVALID
}

var File_components_groupdetails_proto protoreflect.FileDescriptor

const file_components_groupdetails_proto_rawDesc = "" +
	"\n" +
	"\x1dcomponents/groupdetails.proto\x12\n" +
	"components\"c\n" +
	"\fGroupDetails\x12$\n" +
	"\x04team\x18\x01 \x01(\v2\x10.components.TeamR\x04team\x12-\n" +
	"\aechelon\x18\x02 \x01(\v2\x13.components.EchelonR\aechelon\"\x06\n" +
	"\x04Team\"D\n" +
	"\aEchelon\x129\n" +
	"\varmyEchelon\x18\x01 \x01(\x0e2\x17.components.ArmyEchelonR\varmyEchelon*\xaa\x02\n" +
	"\vArmyEchelon\x12\x18\n" +
	"\x14ARMY_ECHELON_INVALID\x10\x00\x12\x1a\n" +
	"\x16ARMY_ECHELON_FIRE_TEAM\x10\x01\x12\x16\n" +
	"\x12ARMY_ECHELON_SQUAD\x10\x02\x12\x18\n" +
	"\x14ARMY_ECHELON_PLATOON\x10\x03\x12\x18\n" +
	"\x14ARMY_ECHELON_COMPANY\x10\x04\x12\x1a\n" +
	"\x16ARMY_ECHELON_BATTALION\x10\x05\x12\x19\n" +
	"\x15ARMY_ECHELON_REGIMENT\x10\x06\x12\x18\n" +
	"\x14ARMY_ECHELON_BRIGADE\x10\a\x12\x19\n" +
	"\x15ARMY_ECHELON_DIVISION\x10\b\x12\x16\n" +
	"\x12ARMY_ECHELON_CORPS\x10\t\x12\x15\n" +
	"\x11ARMY_ECHELON_ARMY\x10\n" +
	"B\rZ\v/componentsb\x06proto3"

var (
	file_components_groupdetails_proto_rawDescOnce sync.Once
	file_components_groupdetails_proto_rawDescData []byte
)

func file_components_groupdetails_proto_rawDescGZIP() []byte {
	file_components_groupdetails_proto_rawDescOnce.Do(func() {
		file_components_groupdetails_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_groupdetails_proto_rawDesc), len(file_components_groupdetails_proto_rawDesc)))
	})
	return file_components_groupdetails_proto_rawDescData
}

var file_components_groupdetails_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_groupdetails_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_groupdetails_proto_goTypes = []any{
	(ArmyEchelon)(0),     // 0: components.ArmyEchelon
	(*GroupDetails)(nil), // 1: components.GroupDetails
	(*Team)(nil),         // 2: components.Team
	(*Echelon)(nil),      // 3: components.Echelon
}
var file_components_groupdetails_proto_depIdxs = []int32{
	2, // 0: components.GroupDetails.team:type_name -> components.Team
	3, // 1: components.GroupDetails.echelon:type_name -> components.Echelon
	0, // 2: components.Echelon.armyEchelon:type_name -> components.ArmyEchelon
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_groupdetails_proto_init() }
func file_components_groupdetails_proto_init() {
	if File_components_groupdetails_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_groupdetails_proto_rawDesc), len(file_components_groupdetails_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_groupdetails_proto_goTypes,
		DependencyIndexes: file_components_groupdetails_proto_depIdxs,
		EnumInfos:         file_components_groupdetails_proto_enumTypes,
		MessageInfos:      file_components_groupdetails_proto_msgTypes,
	}.Build()
	File_components_groupdetails_proto = out.File
	file_components_groupdetails_proto_goTypes = nil
	file_components_groupdetails_proto_depIdxs = nil
}
