// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/location_uncertainty.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationUncertainty struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PositionEnuCov *PositionEnuCov        `protobuf:"bytes,1,opt,name=positionEnuCov,proto3" json:"positionEnuCov,omitempty"`
	VelocityEnuCov *VelocityEnuCov        `protobuf:"bytes,2,opt,name=velocityEnuCov,proto3" json:"velocityEnuCov,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationUncertainty) Reset() {
	*x = LocationUncertainty{}
	mi := &file_components_location_uncertainty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUncertainty) ProtoMessage() {}

func (x *LocationUncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUncertainty.ProtoReflect.Descriptor instead.
func (*LocationUncertainty) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{0}
}

func (x *LocationUncertainty) GetPositionEnuCov() *PositionEnuCov {
	if x != nil {
		return x.PositionEnuCov
	}
	return nil
}

func (x *LocationUncertainty) GetVelocityEnuCov() *VelocityEnuCov {
	if x != nil {
		return x.VelocityEnuCov
	}
	return nil
}

type PositionEnuCov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mxx           float32                `protobuf:"fixed32,1,opt,name=mxx,proto3" json:"mxx,omitempty"`
	Mxy           float32                `protobuf:"fixed32,2,opt,name=mxy,proto3" json:"mxy,omitempty"`
	Mxz           float32                `protobuf:"fixed32,3,opt,name=mxz,proto3" json:"mxz,omitempty"`
	Myy           float32                `protobuf:"fixed32,4,opt,name=myy,proto3" json:"myy,omitempty"`
	Myz           float32                `protobuf:"fixed32,5,opt,name=myz,proto3" json:"myz,omitempty"`
	Mzz           float32                `protobuf:"fixed32,6,opt,name=mzz,proto3" json:"mzz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionEnuCov) Reset() {
	*x = PositionEnuCov{}
	mi := &file_components_location_uncertainty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionEnuCov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionEnuCov) ProtoMessage() {}

func (x *PositionEnuCov) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionEnuCov.ProtoReflect.Descriptor instead.
func (*PositionEnuCov) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{1}
}

func (x *PositionEnuCov) GetMxx() float32 {
	if x != nil {
		return x.Mxx
	}
	return 0
}

func (x *PositionEnuCov) GetMxy() float32 {
	if x != nil {
		return x.Mxy
	}
	return 0
}

func (x *PositionEnuCov) GetMxz() float32 {
	if x != nil {
		return x.Mxz
	}
	return 0
}

func (x *PositionEnuCov) GetMyy() float32 {
	if x != nil {
		return x.Myy
	}
	return 0
}

func (x *PositionEnuCov) GetMyz() float32 {
	if x != nil {
		return x.Myz
	}
	return 0
}

func (x *PositionEnuCov) GetMzz() float32 {
	if x != nil {
		return x.Mzz
	}
	return 0
}

type VelocityEnuCov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mxx           float32                `protobuf:"fixed32,1,opt,name=mxx,proto3" json:"mxx,omitempty"`
	Mxy           float32                `protobuf:"fixed32,2,opt,name=mxy,proto3" json:"mxy,omitempty"`
	Mxz           float32                `protobuf:"fixed32,3,opt,name=mxz,proto3" json:"mxz,omitempty"`
	Myy           float32                `protobuf:"fixed32,4,opt,name=myy,proto3" json:"myy,omitempty"`
	Myz           float32                `protobuf:"fixed32,5,opt,name=myz,proto3" json:"myz,omitempty"`
	Mzz           float32                `protobuf:"fixed32,6,opt,name=mzz,proto3" json:"mzz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VelocityEnuCov) Reset() {
	*x = VelocityEnuCov{}
	mi := &file_components_location_uncertainty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VelocityEnuCov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VelocityEnuCov) ProtoMessage() {}

func (x *VelocityEnuCov) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VelocityEnuCov.ProtoReflect.Descriptor instead.
func (*VelocityEnuCov) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{2}
}

func (x *VelocityEnuCov) GetMxx() float32 {
	if x != nil {
		return x.Mxx
	}
	return 0
}

func (x *VelocityEnuCov) GetMxy() float32 {
	if x != nil {
		return x.Mxy
	}
	return 0
}

func (x *VelocityEnuCov) GetMxz() float32 {
	if x != nil {
		return x.Mxz
	}
	return 0
}

func (x *VelocityEnuCov) GetMyy() float32 {
	if x != nil {
		return x.Myy
	}
	return 0
}

func (x *VelocityEnuCov) GetMyz() float32 {
	if x != nil {
		return x.Myz
	}
	return 0
}

func (x *VelocityEnuCov) GetMzz() float32 {
	if x != nil {
		return x.Mzz
	}
	return 0
}

type PositionErrorEllipse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Probability    float64                `protobuf:"fixed64,1,opt,name=probability,proto3" json:"probability,omitempty"`
	SemiMajorAxisM float64                `protobuf:"fixed64,2,opt,name=semiMajorAxisM,proto3" json:"semiMajorAxisM,omitempty"`
	SemiMinorAxisM float64                `protobuf:"fixed64,3,opt,name=semiMinorAxisM,proto3" json:"semiMinorAxisM,omitempty"`
	OrientationD   float64                `protobuf:"fixed64,4,opt,name=orientationD,proto3" json:"orientationD,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PositionErrorEllipse) Reset() {
	*x = PositionErrorEllipse{}
	mi := &file_components_location_uncertainty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionErrorEllipse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionErrorEllipse) ProtoMessage() {}

func (x *PositionErrorEllipse) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionErrorEllipse.ProtoReflect.Descriptor instead.
func (*PositionErrorEllipse) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{3}
}

func (x *PositionErrorEllipse) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *PositionErrorEllipse) GetSemiMajorAxisM() float64 {
	if x != nil {
		return x.SemiMajorAxisM
	}
	return 0
}

func (x *PositionErrorEllipse) GetSemiMinorAxisM() float64 {
	if x != nil {
		return x.SemiMinorAxisM
	}
	return 0
}

func (x *PositionErrorEllipse) GetOrientationD() float64 {
	if x != nil {
		return x.OrientationD
	}
	return 0
}

var File_components_location_uncertainty_proto protoreflect.FileDescriptor

const file_components_location_uncertainty_proto_rawDesc = "" +
	"\n" +
	"%components/location_uncertainty.proto\x12\n" +
	"components\"\x9d\x01\n" +
	"\x13LocationUncertainty\x12B\n" +
	"\x0epositionEnuCov\x18\x01 \x01(\v2\x1a.components.PositionEnuCovR\x0epositionEnuCov\x12B\n" +
	"\x0evelocityEnuCov\x18\x02 \x01(\v2\x1a.components.VelocityEnuCovR\x0evelocityEnuCov\"|\n" +
	"\x0ePositionEnuCov\x12\x10\n" +
	"\x03mxx\x18\x01 \x01(\x02R\x03mxx\x12\x10\n" +
	"\x03mxy\x18\x02 \x01(\x02R\x03mxy\x12\x10\n" +
	"\x03mxz\x18\x03 \x01(\x02R\x03mxz\x12\x10\n" +
	"\x03myy\x18\x04 \x01(\x02R\x03myy\x12\x10\n" +
	"\x03myz\x18\x05 \x01(\x02R\x03myz\x12\x10\n" +
	"\x03mzz\x18\x06 \x01(\x02R\x03mzz\"|\n" +
	"\x0eVelocityEnuCov\x12\x10\n" +
	"\x03mxx\x18\x01 \x01(\x02R\x03mxx\x12\x10\n" +
	"\x03mxy\x18\x02 \x01(\x02R\x03mxy\x12\x10\n" +
	"\x03mxz\x18\x03 \x01(\x02R\x03mxz\x12\x10\n" +
	"\x03myy\x18\x04 \x01(\x02R\x03myy\x12\x10\n" +
	"\x03myz\x18\x05 \x01(\x02R\x03myz\x12\x10\n" +
	"\x03mzz\x18\x06 \x01(\x02R\x03mzz\"\xac\x01\n" +
	"\x14PositionErrorEllipse\x12 \n" +
	"\vprobability\x18\x01 \x01(\x01R\vprobability\x12&\n" +
	"\x0esemiMajorAxisM\x18\x02 \x01(\x01R\x0esemiMajorAxisM\x12&\n" +
	"\x0esemiMinorAxisM\x18\x03 \x01(\x01R\x0esemiMinorAxisM\x12\"\n" +
	"\forientationD\x18\x04 \x01(\x01R\forientationDB\rZ\v/componentsb\x06proto3"

var (
	file_components_location_uncertainty_proto_rawDescOnce sync.Once
	file_components_location_uncertainty_proto_rawDescData []byte
)

func file_components_location_uncertainty_proto_rawDescGZIP() []byte {
	file_components_location_uncertainty_proto_rawDescOnce.Do(func() {
		file_components_location_uncertainty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_location_uncertainty_proto_rawDesc), len(file_components_location_uncertainty_proto_rawDesc)))
	})
	return file_components_location_uncertainty_proto_rawDescData
}

var file_components_location_uncertainty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_location_uncertainty_proto_goTypes = []any{
	(*LocationUncertainty)(nil),  // 0: components.LocationUncertainty
	(*PositionEnuCov)(nil),       // 1: components.PositionEnuCov
	(*VelocityEnuCov)(nil),       // 2: components.VelocityEnuCov
	(*PositionErrorEllipse)(nil), // 3: components.PositionErrorEllipse
}
var file_components_location_uncertainty_proto_depIdxs = []int32{
	1, // 0: components.LocationUncertainty.positionEnuCov:type_name -> components.PositionEnuCov
	2, // 1: components.LocationUncertainty.velocityEnuCov:type_name -> components.VelocityEnuCov
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_components_location_uncertainty_proto_init() }
func file_components_location_uncertainty_proto_init() {
	if File_components_location_uncertainty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_location_uncertainty_proto_rawDesc), len(file_components_location_uncertainty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_location_uncertainty_proto_goTypes,
		DependencyIndexes: file_components_location_uncertainty_proto_depIdxs,
		MessageInfos:      file_components_location_uncertainty_proto_msgTypes,
	}.Build()
	File_components_location_uncertainty_proto = out.File
	file_components_location_uncertainty_proto_goTypes = nil
	file_components_location_uncertainty_proto_depIdxs = nil
}
