// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/orbit.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefFrame int32

const (
	RefFrame_ECI_REFERENCE_FRAME_INVALID RefFrame = 0
	RefFrame_ECI_REFERENCE_FRAME_TEME    RefFrame = 1
)

// Enum value maps for RefFrame.
var (
	RefFrame_name = map[int32]string{
		0: "ECI_REFERENCE_FRAME_INVALID",
		1: "ECI_REFERENCE_FRAME_TEME",
	}
	RefFrame_value = map[string]int32{
		"ECI_REFERENCE_FRAME_INVALID": 0,
		"ECI_REFERENCE_FRAME_TEME":    1,
	}
)

func (x RefFrame) Enum() *RefFrame {
	p := new(RefFrame)
	*p = x
	return p
}

func (x RefFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_components_orbit_proto_enumTypes[0].Descriptor()
}

func (RefFrame) Type() protoreflect.EnumType {
	return &file_components_orbit_proto_enumTypes[0]
}

func (x RefFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefFrame.Descriptor instead.
func (RefFrame) EnumDescriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{0}
}

type MeanElementTheory int32

const (
	MeanElementTheory_MEAN_ELEMENT_THEORY_INVALID MeanElementTheory = 0
	MeanElementTheory_MEAN_ELEMENT_THEORY_SGP4    MeanElementTheory = 1
)

// Enum value maps for MeanElementTheory.
var (
	MeanElementTheory_name = map[int32]string{
		0: "MEAN_ELEMENT_THEORY_INVALID",
		1: "MEAN_ELEMENT_THEORY_SGP4",
	}
	MeanElementTheory_value = map[string]int32{
		"MEAN_ELEMENT_THEORY_INVALID": 0,
		"MEAN_ELEMENT_THEORY_SGP4":    1,
	}
)

func (x MeanElementTheory) Enum() *MeanElementTheory {
	p := new(MeanElementTheory)
	*p = x
	return p
}

func (x MeanElementTheory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeanElementTheory) Descriptor() protoreflect.EnumDescriptor {
	return file_components_orbit_proto_enumTypes[1].Descriptor()
}

func (MeanElementTheory) Type() protoreflect.EnumType {
	return &file_components_orbit_proto_enumTypes[1]
}

func (x MeanElementTheory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeanElementTheory.Descriptor instead.
func (MeanElementTheory) EnumDescriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{1}
}

type Orbit struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrbitMeanElements *OrbitMeanElements     `protobuf:"bytes,1,opt,name=orbitMeanElements,proto3" json:"orbitMeanElements,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Orbit) Reset() {
	*x = Orbit{}
	mi := &file_components_orbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orbit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orbit) ProtoMessage() {}

func (x *Orbit) ProtoReflect() protoreflect.Message {
	mi := &file_components_orbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orbit.ProtoReflect.Descriptor instead.
func (*Orbit) Descriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{0}
}

func (x *Orbit) GetOrbitMeanElements() *OrbitMeanElements {
	if x != nil {
		return x.OrbitMeanElements
	}
	return nil
}

type OrbitMeanElements struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Metadata              *OrbitMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MeanKeplarianElements *MeanKeplarianElements `protobuf:"bytes,2,opt,name=meanKeplarianElements,proto3" json:"meanKeplarianElements,omitempty"`
	TleParameters         *TleParamaters         `protobuf:"bytes,3,opt,name=tleParameters,proto3" json:"tleParameters,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrbitMeanElements) Reset() {
	*x = OrbitMeanElements{}
	mi := &file_components_orbit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbitMeanElements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitMeanElements) ProtoMessage() {}

func (x *OrbitMeanElements) ProtoReflect() protoreflect.Message {
	mi := &file_components_orbit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitMeanElements.ProtoReflect.Descriptor instead.
func (*OrbitMeanElements) Descriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{1}
}

func (x *OrbitMeanElements) GetMetadata() *OrbitMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OrbitMeanElements) GetMeanKeplarianElements() *MeanKeplarianElements {
	if x != nil {
		return x.MeanKeplarianElements
	}
	return nil
}

func (x *OrbitMeanElements) GetTleParameters() *TleParamaters {
	if x != nil {
		return x.TleParameters
	}
	return nil
}

type OrbitMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CreationDate      string                 `protobuf:"bytes,1,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	Originator        string                 `protobuf:"bytes,2,opt,name=originator,proto3" json:"originator,omitempty"`
	MessageId         string                 `protobuf:"bytes,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	RefFrame          RefFrame               `protobuf:"varint,4,opt,name=refFrame,proto3,enum=components.RefFrame" json:"refFrame,omitempty"`
	RefFrameEpoch     string                 `protobuf:"bytes,5,opt,name=refFrameEpoch,proto3" json:"refFrameEpoch,omitempty"`
	MeanElementTheory MeanElementTheory      `protobuf:"varint,6,opt,name=meanElementTheory,proto3,enum=components.MeanElementTheory" json:"meanElementTheory,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrbitMetadata) Reset() {
	*x = OrbitMetadata{}
	mi := &file_components_orbit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbitMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitMetadata) ProtoMessage() {}

func (x *OrbitMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_components_orbit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitMetadata.ProtoReflect.Descriptor instead.
func (*OrbitMetadata) Descriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{2}
}

func (x *OrbitMetadata) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *OrbitMetadata) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *OrbitMetadata) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OrbitMetadata) GetRefFrame() RefFrame {
	if x != nil {
		return x.RefFrame
	}
	return RefFrame_ECI_REFERENCE_FRAME_INVALID
}

func (x *OrbitMetadata) GetRefFrameEpoch() string {
	if x != nil {
		return x.RefFrameEpoch
	}
	return ""
}

func (x *OrbitMetadata) GetMeanElementTheory() MeanElementTheory {
	if x != nil {
		return x.MeanElementTheory
	}
	return MeanElementTheory_MEAN_ELEMENT_THEORY_INVALID
}

type MeanKeplarianElements struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Epoch              string                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SemiMajorAxisKm    float64                `protobuf:"fixed64,2,opt,name=semiMajorAxisKm,proto3" json:"semiMajorAxisKm,omitempty"`
	MeanMotion         float64                `protobuf:"fixed64,3,opt,name=meanMotion,proto3" json:"meanMotion,omitempty"`
	Eccentricity       float64                `protobuf:"fixed64,4,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	InclinationDeg     float64                `protobuf:"fixed64,5,opt,name=inclinationDeg,proto3" json:"inclinationDeg,omitempty"`
	RaOfAscNodeDeg     float64                `protobuf:"fixed64,6,opt,name=raOfAscNodeDeg,proto3" json:"raOfAscNodeDeg,omitempty"`
	ArgOfPericenterDeg float64                `protobuf:"fixed64,7,opt,name=argOfPericenterDeg,proto3" json:"argOfPericenterDeg,omitempty"`
	MeanAnomalyDeg     float64                `protobuf:"fixed64,8,opt,name=meanAnomalyDeg,proto3" json:"meanAnomalyDeg,omitempty"`
	Gm                 float64                `protobuf:"fixed64,9,opt,name=gm,proto3" json:"gm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MeanKeplarianElements) Reset() {
	*x = MeanKeplarianElements{}
	mi := &file_components_orbit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeanKeplarianElements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeanKeplarianElements) ProtoMessage() {}

func (x *MeanKeplarianElements) ProtoReflect() protoreflect.Message {
	mi := &file_components_orbit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeanKeplarianElements.ProtoReflect.Descriptor instead.
func (*MeanKeplarianElements) Descriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{3}
}

func (x *MeanKeplarianElements) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *MeanKeplarianElements) GetSemiMajorAxisKm() float64 {
	if x != nil {
		return x.SemiMajorAxisKm
	}
	return 0
}

func (x *MeanKeplarianElements) GetMeanMotion() float64 {
	if x != nil {
		return x.MeanMotion
	}
	return 0
}

func (x *MeanKeplarianElements) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *MeanKeplarianElements) GetInclinationDeg() float64 {
	if x != nil {
		return x.InclinationDeg
	}
	return 0
}

func (x *MeanKeplarianElements) GetRaOfAscNodeDeg() float64 {
	if x != nil {
		return x.RaOfAscNodeDeg
	}
	return 0
}

func (x *MeanKeplarianElements) GetArgOfPericenterDeg() float64 {
	if x != nil {
		return x.ArgOfPericenterDeg
	}
	return 0
}

func (x *MeanKeplarianElements) GetMeanAnomalyDeg() float64 {
	if x != nil {
		return x.MeanAnomalyDeg
	}
	return 0
}

func (x *MeanKeplarianElements) GetGm() float64 {
	if x != nil {
		return x.Gm
	}
	return 0
}

type TleParamaters struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EphemerisType      uint32                 `protobuf:"varint,1,opt,name=ephemerisType,proto3" json:"ephemerisType,omitempty"`
	ClassificationType string                 `protobuf:"bytes,2,opt,name=classificationType,proto3" json:"classificationType,omitempty"`
	NoradCatId         uint32                 `protobuf:"varint,3,opt,name=noradCatId,proto3" json:"noradCatId,omitempty"`
	ElementSetNo       uint32                 `protobuf:"varint,4,opt,name=elementSetNo,proto3" json:"elementSetNo,omitempty"`
	RevAtEpoch         uint32                 `protobuf:"varint,5,opt,name=revAtEpoch,proto3" json:"revAtEpoch,omitempty"`
	Bstar              float64                `protobuf:"fixed64,6,opt,name=bstar,proto3" json:"bstar,omitempty"`
	Bterm              float64                `protobuf:"fixed64,7,opt,name=bterm,proto3" json:"bterm,omitempty"`
	MeanMotionDot      float64                `protobuf:"fixed64,8,opt,name=meanMotionDot,proto3" json:"meanMotionDot,omitempty"`
	MeanMotionDdot     float64                `protobuf:"fixed64,9,opt,name=meanMotionDdot,proto3" json:"meanMotionDdot,omitempty"`
	Agom               float64                `protobuf:"fixed64,10,opt,name=agom,proto3" json:"agom,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TleParamaters) Reset() {
	*x = TleParamaters{}
	mi := &file_components_orbit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TleParamaters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TleParamaters) ProtoMessage() {}

func (x *TleParamaters) ProtoReflect() protoreflect.Message {
	mi := &file_components_orbit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TleParamaters.ProtoReflect.Descriptor instead.
func (*TleParamaters) Descriptor() ([]byte, []int) {
	return file_components_orbit_proto_rawDescGZIP(), []int{4}
}

func (x *TleParamaters) GetEphemerisType() uint32 {
	if x != nil {
		return x.EphemerisType
	}
	return 0
}

func (x *TleParamaters) GetClassificationType() string {
	if x != nil {
		return x.ClassificationType
	}
	return ""
}

func (x *TleParamaters) GetNoradCatId() uint32 {
	if x != nil {
		return x.NoradCatId
	}
	return 0
}

func (x *TleParamaters) GetElementSetNo() uint32 {
	if x != nil {
		return x.ElementSetNo
	}
	return 0
}

func (x *TleParamaters) GetRevAtEpoch() uint32 {
	if x != nil {
		return x.RevAtEpoch
	}
	return 0
}

func (x *TleParamaters) GetBstar() float64 {
	if x != nil {
		return x.Bstar
	}
	return 0
}

func (x *TleParamaters) GetBterm() float64 {
	if x != nil {
		return x.Bterm
	}
	return 0
}

func (x *TleParamaters) GetMeanMotionDot() float64 {
	if x != nil {
		return x.MeanMotionDot
	}
	return 0
}

func (x *TleParamaters) GetMeanMotionDdot() float64 {
	if x != nil {
		return x.MeanMotionDdot
	}
	return 0
}

func (x *TleParamaters) GetAgom() float64 {
	if x != nil {
		return x.Agom
	}
	return 0
}

var File_components_orbit_proto protoreflect.FileDescriptor

const file_components_orbit_proto_rawDesc = "" +
	"\n" +
	"\x16components/orbit.proto\x12\n" +
	"components\"T\n" +
	"\x05Orbit\x12K\n" +
	"\x11orbitMeanElements\x18\x01 \x01(\v2\x1d.components.OrbitMeanElementsR\x11orbitMeanElements\"\xe4\x01\n" +
	"\x11OrbitMeanElements\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.components.OrbitMetadataR\bmetadata\x12W\n" +
	"\x15meanKeplarianElements\x18\x02 \x01(\v2!.components.MeanKeplarianElementsR\x15meanKeplarianElements\x12?\n" +
	"\rtleParameters\x18\x03 \x01(\v2\x19.components.TleParamatersR\rtleParameters\"\x96\x02\n" +
	"\rOrbitMetadata\x12\"\n" +
	"\fcreationDate\x18\x01 \x01(\tR\fcreationDate\x12\x1e\n" +
	"\n" +
	"originator\x18\x02 \x01(\tR\n" +
	"originator\x12\x1c\n" +
	"\tmessageId\x18\x03 \x01(\tR\tmessageId\x120\n" +
	"\brefFrame\x18\x04 \x01(\x0e2\x14.components.RefFrameR\brefFrame\x12$\n" +
	"\rrefFrameEpoch\x18\x05 \x01(\tR\rrefFrameEpoch\x12K\n" +
	"\x11meanElementTheory\x18\x06 \x01(\x0e2\x1d.components.MeanElementTheoryR\x11meanElementTheory\"\xd3\x02\n" +
	"\x15MeanKeplarianElements\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\tR\x05epoch\x12(\n" +
	"\x0fsemiMajorAxisKm\x18\x02 \x01(\x01R\x0fsemiMajorAxisKm\x12\x1e\n" +
	"\n" +
	"meanMotion\x18\x03 \x01(\x01R\n" +
	"meanMotion\x12\"\n" +
	"\feccentricity\x18\x04 \x01(\x01R\feccentricity\x12&\n" +
	"\x0einclinationDeg\x18\x05 \x01(\x01R\x0einclinationDeg\x12&\n" +
	"\x0eraOfAscNodeDeg\x18\x06 \x01(\x01R\x0eraOfAscNodeDeg\x12.\n" +
	"\x12argOfPericenterDeg\x18\a \x01(\x01R\x12argOfPericenterDeg\x12&\n" +
	"\x0emeanAnomalyDeg\x18\b \x01(\x01R\x0emeanAnomalyDeg\x12\x0e\n" +
	"\x02gm\x18\t \x01(\x01R\x02gm\"\xd7\x02\n" +
	"\rTleParamaters\x12$\n" +
	"\rephemerisType\x18\x01 \x01(\rR\rephemerisType\x12.\n" +
	"\x12classificationType\x18\x02 \x01(\tR\x12classificationType\x12\x1e\n" +
	"\n" +
	"noradCatId\x18\x03 \x01(\rR\n" +
	"noradCatId\x12\"\n" +
	"\felementSetNo\x18\x04 \x01(\rR\felementSetNo\x12\x1e\n" +
	"\n" +
	"revAtEpoch\x18\x05 \x01(\rR\n" +
	"revAtEpoch\x12\x14\n" +
	"\x05bstar\x18\x06 \x01(\x01R\x05bstar\x12\x14\n" +
	"\x05bterm\x18\a \x01(\x01R\x05bterm\x12$\n" +
	"\rmeanMotionDot\x18\b \x01(\x01R\rmeanMotionDot\x12&\n" +
	"\x0emeanMotionDdot\x18\t \x01(\x01R\x0emeanMotionDdot\x12\x12\n" +
	"\x04agom\x18\n" +
	" \x01(\x01R\x04agom*I\n" +
	"\bRefFrame\x12\x1f\n" +
	"\x1bECI_REFERENCE_FRAME_INVALID\x10\x00\x12\x1c\n" +
	"\x18ECI_REFERENCE_FRAME_TEME\x10\x01*R\n" +
	"\x11MeanElementTheory\x12\x1f\n" +
	"\x1bMEAN_ELEMENT_THEORY_INVALID\x10\x00\x12\x1c\n" +
	"\x18MEAN_ELEMENT_THEORY_SGP4\x10\x01B\rZ\v/componentsb\x06proto3"

var (
	file_components_orbit_proto_rawDescOnce sync.Once
	file_components_orbit_proto_rawDescData []byte
)

func file_components_orbit_proto_rawDescGZIP() []byte {
	file_components_orbit_proto_rawDescOnce.Do(func() {
		file_components_orbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_orbit_proto_rawDesc), len(file_components_orbit_proto_rawDesc)))
	})
	return file_components_orbit_proto_rawDescData
}

var file_components_orbit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_components_orbit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_components_orbit_proto_goTypes = []any{
	(RefFrame)(0),                 // 0: components.RefFrame
	(MeanElementTheory)(0),        // 1: components.MeanElementTheory
	(*Orbit)(nil),                 // 2: components.Orbit
	(*OrbitMeanElements)(nil),     // 3: components.OrbitMeanElements
	(*OrbitMetadata)(nil),         // 4: components.OrbitMetadata
	(*MeanKeplarianElements)(nil), // 5: components.MeanKeplarianElements
	(*TleParamaters)(nil),         // 6: components.TleParamaters
}
var file_components_orbit_proto_depIdxs = []int32{
	3, // 0: components.Orbit.orbitMeanElements:type_name -> components.OrbitMeanElements
	4, // 1: components.OrbitMeanElements.metadata:type_name -> components.OrbitMetadata
	5, // 2: components.OrbitMeanElements.meanKeplarianElements:type_name -> components.MeanKeplarianElements
	6, // 3: components.OrbitMeanElements.tleParameters:type_name -> components.TleParamaters
	0, // 4: components.OrbitMetadata.refFrame:type_name -> components.RefFrame
	1, // 5: components.OrbitMetadata.meanElementTheory:type_name -> components.MeanElementTheory
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_components_orbit_proto_init() }
func file_components_orbit_proto_init() {
	if File_components_orbit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_orbit_proto_rawDesc), len(file_components_orbit_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_orbit_proto_goTypes,
		DependencyIndexes: file_components_orbit_proto_depIdxs,
		EnumInfos:         file_components_orbit_proto_enumTypes,
		MessageInfos:      file_components_orbit_proto_msgTypes,
	}.Build()
	File_components_orbit_proto = out.File
	file_components_orbit_proto_goTypes = nil
	file_components_orbit_proto_depIdxs = nil
}
