// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/position.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WGS84 geodetic latitude in decimal degrees.
	LatitudeDegrees float64 `protobuf:"fixed64,1,opt,name=latitudeDegrees,proto3" json:"latitudeDegrees,omitempty"`
	// WGS84 longitude in decimal degrees.
	LongitudeDegrees float64 `protobuf:"fixed64,2,opt,name=longitudeDegrees,proto3" json:"longitudeDegrees,omitempty"`
	// Altitude as height above ellipsoid (WGS84) in meters.
	AltitudeHaeMeters float64 `protobuf:"fixed64,3,opt,name=altitudeHaeMeters,proto3" json:"altitudeHaeMeters,omitempty"`
	// Altitude as AGL (Above Ground Level).
	AltitudeAglMeters float64 `protobuf:"fixed64,4,opt,name=altitudeAglMeters,proto3" json:"altitudeAglMeters,omitempty"`
	// Altitude as ASF (Above Sea Floor).
	AltitudeAsfMeters float64 `protobuf:"fixed64,5,opt,name=altitudeAsfMeters,proto3" json:"altitudeAsfMeters,omitempty"`
	// Depth from surface of water via pressure sensors.
	PressureDepthMeters float64 `protobuf:"fixed64,6,opt,name=pressureDepthMeters,proto3" json:"pressureDepthMeters,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_components_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_components_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_components_position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLatitudeDegrees() float64 {
	if x != nil {
		return x.LatitudeDegrees
	}
	return 0
}

func (x *Position) GetLongitudeDegrees() float64 {
	if x != nil {
		return x.LongitudeDegrees
	}
	return 0
}

func (x *Position) GetAltitudeHaeMeters() float64 {
	if x != nil {
		return x.AltitudeHaeMeters
	}
	return 0
}

func (x *Position) GetAltitudeAglMeters() float64 {
	if x != nil {
		return x.AltitudeAglMeters
	}
	return 0
}

func (x *Position) GetAltitudeAsfMeters() float64 {
	if x != nil {
		return x.AltitudeAsfMeters
	}
	return 0
}

func (x *Position) GetPressureDepthMeters() float64 {
	if x != nil {
		return x.PressureDepthMeters
	}
	return 0
}

var File_components_position_proto protoreflect.FileDescriptor

const file_components_position_proto_rawDesc = "" +
	"\n" +
	"\x19components/position.proto\x12\n" +
	"components\"\x9c\x02\n" +
	"\bPosition\x12(\n" +
	"\x0flatitudeDegrees\x18\x01 \x01(\x01R\x0flatitudeDegrees\x12*\n" +
	"\x10longitudeDegrees\x18\x02 \x01(\x01R\x10longitudeDegrees\x12,\n" +
	"\x11altitudeHaeMeters\x18\x03 \x01(\x01R\x11altitudeHaeMeters\x12,\n" +
	"\x11altitudeAglMeters\x18\x04 \x01(\x01R\x11altitudeAglMeters\x12,\n" +
	"\x11altitudeAsfMeters\x18\x05 \x01(\x01R\x11altitudeAsfMeters\x120\n" +
	"\x13pressureDepthMeters\x18\x06 \x01(\x01R\x13pressureDepthMetersB\rZ\v/componentsb\x06proto3"

var (
	file_components_position_proto_rawDescOnce sync.Once
	file_components_position_proto_rawDescData []byte
)

func file_components_position_proto_rawDescGZIP() []byte {
	file_components_position_proto_rawDescOnce.Do(func() {
		file_components_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_position_proto_rawDesc), len(file_components_position_proto_rawDesc)))
	})
	return file_components_position_proto_rawDescData
}

var file_components_position_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_position_proto_goTypes = []any{
	(*Position)(nil), // 0: components.Position
}
var file_components_position_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_components_position_proto_init() }
func file_components_position_proto_init() {
	if File_components_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_position_proto_rawDesc), len(file_components_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_position_proto_goTypes,
		DependencyIndexes: file_components_position_proto_depIdxs,
		MessageInfos:      file_components_position_proto_msgTypes,
	}.Build()
	File_components_position_proto = out.File
	file_components_position_proto_goTypes = nil
	file_components_position_proto_depIdxs = nil
}
