// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/schedules.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleType int32

const (
	ScheduleType_SCHEDULE_TYPE_INVALID           ScheduleType = 0
	ScheduleType_SCHEDULE_TYPE_ZONE_ENABLED      ScheduleType = 1
	ScheduleType_SCHEDULE_TYPE_ZONE_TEMP_ENABLED ScheduleType = 2
)

// Enum value maps for ScheduleType.
var (
	ScheduleType_name = map[int32]string{
		0: "SCHEDULE_TYPE_INVALID",
		1: "SCHEDULE_TYPE_ZONE_ENABLED",
		2: "SCHEDULE_TYPE_ZONE_TEMP_ENABLED",
	}
	ScheduleType_value = map[string]int32{
		"SCHEDULE_TYPE_INVALID":           0,
		"SCHEDULE_TYPE_ZONE_ENABLED":      1,
		"SCHEDULE_TYPE_ZONE_TEMP_ENABLED": 2,
	}
)

func (x ScheduleType) Enum() *ScheduleType {
	p := new(ScheduleType)
	*p = x
	return p
}

func (x ScheduleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_schedules_proto_enumTypes[0].Descriptor()
}

func (ScheduleType) Type() protoreflect.EnumType {
	return &file_components_schedules_proto_enumTypes[0]
}

func (x ScheduleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleType.Descriptor instead.
func (ScheduleType) EnumDescriptor() ([]byte, []int) {
	return file_components_schedules_proto_rawDescGZIP(), []int{0}
}

type Schedules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedules) Reset() {
	*x = Schedules{}
	mi := &file_components_schedules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedules) ProtoMessage() {}

func (x *Schedules) ProtoReflect() protoreflect.Message {
	mi := &file_components_schedules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedules.ProtoReflect.Descriptor instead.
func (*Schedules) Descriptor() ([]byte, []int) {
	return file_components_schedules_proto_rawDescGZIP(), []int{0}
}

func (x *Schedules) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Windows       []*Window              `protobuf:"bytes,1,rep,name=windows,proto3" json:"windows,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	ScheduleType  ScheduleType           `protobuf:"varint,3,opt,name=scheduleType,proto3,enum=components.ScheduleType" json:"scheduleType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_components_schedules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_components_schedules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_components_schedules_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetWindows() []*Window {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetScheduleType() ScheduleType {
	if x != nil {
		return x.ScheduleType
	}
	return ScheduleType_SCHEDULE_TYPE_INVALID
}

type Window struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// in UTC, describes when and at what cadence this window starts, in the quartz flavor of cron
	CronExpression string `protobuf:"bytes,1,opt,name=cronExpression,proto3" json:"cronExpression,omitempty"`
	// describes the duration
	DurationMillis string `protobuf:"bytes,2,opt,name=durationMillis,proto3" json:"durationMillis,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Window) Reset() {
	*x = Window{}
	mi := &file_components_schedules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Window) ProtoMessage() {}

func (x *Window) ProtoReflect() protoreflect.Message {
	mi := &file_components_schedules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Window.ProtoReflect.Descriptor instead.
func (*Window) Descriptor() ([]byte, []int) {
	return file_components_schedules_proto_rawDescGZIP(), []int{2}
}

func (x *Window) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *Window) GetDurationMillis() string {
	if x != nil {
		return x.DurationMillis
	}
	return ""
}

var File_components_schedules_proto protoreflect.FileDescriptor

const file_components_schedules_proto_rawDesc = "" +
	"\n" +
	"\x1acomponents/schedules.proto\x12\n" +
	"components\"?\n" +
	"\tSchedules\x122\n" +
	"\tschedules\x18\x01 \x03(\v2\x14.components.ScheduleR\tschedules\"\x96\x01\n" +
	"\bSchedule\x12,\n" +
	"\awindows\x18\x01 \x03(\v2\x12.components.WindowR\awindows\x12\x1e\n" +
	"\n" +
	"scheduleId\x18\x02 \x01(\tR\n" +
	"scheduleId\x12<\n" +
	"\fscheduleType\x18\x03 \x01(\x0e2\x18.components.ScheduleTypeR\fscheduleType\"X\n" +
	"\x06Window\x12&\n" +
	"\x0ecronExpression\x18\x01 \x01(\tR\x0ecronExpression\x12&\n" +
	"\x0edurationMillis\x18\x02 \x01(\tR\x0edurationMillis*n\n" +
	"\fScheduleType\x12\x19\n" +
	"\x15SCHEDULE_TYPE_INVALID\x10\x00\x12\x1e\n" +
	"\x1aSCHEDULE_TYPE_ZONE_ENABLED\x10\x01\x12#\n" +
	"\x1fSCHEDULE_TYPE_ZONE_TEMP_ENABLED\x10\x02B\rZ\v/componentsb\x06proto3"

var (
	file_components_schedules_proto_rawDescOnce sync.Once
	file_components_schedules_proto_rawDescData []byte
)

func file_components_schedules_proto_rawDescGZIP() []byte {
	file_components_schedules_proto_rawDescOnce.Do(func() {
		file_components_schedules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_schedules_proto_rawDesc), len(file_components_schedules_proto_rawDesc)))
	})
	return file_components_schedules_proto_rawDescData
}

var file_components_schedules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_schedules_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_schedules_proto_goTypes = []any{
	(ScheduleType)(0), // 0: components.ScheduleType
	(*Schedules)(nil), // 1: components.Schedules
	(*Schedule)(nil),  // 2: components.Schedule
	(*Window)(nil),    // 3: components.Window
}
var file_components_schedules_proto_depIdxs = []int32{
	2, // 0: components.Schedules.schedules:type_name -> components.Schedule
	3, // 1: components.Schedule.windows:type_name -> components.Window
	0, // 2: components.Schedule.scheduleType:type_name -> components.ScheduleType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_schedules_proto_init() }
func file_components_schedules_proto_init() {
	if File_components_schedules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_schedules_proto_rawDesc), len(file_components_schedules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_schedules_proto_goTypes,
		DependencyIndexes: file_components_schedules_proto_depIdxs,
		EnumInfos:         file_components_schedules_proto_enumTypes,
		MessageInfos:      file_components_schedules_proto_msgTypes,
	}.Build()
	File_components_schedules_proto = out.File
	file_components_schedules_proto_goTypes = nil
	file_components_schedules_proto_depIdxs = nil
}
