// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/aliases.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for AltIDType
type AltIDType int32

const (
	AltIDType_ALT_ID_TYPE_INVALID             AltIDType = 0
	AltIDType_ALT_ID_TYPE_TRACK_ID_2          AltIDType = 1
	AltIDType_ALT_ID_TYPE_TRACK_ID_1          AltIDType = 2
	AltIDType_ALT_ID_TYPE_SPI_ID              AltIDType = 3
	AltIDType_ALT_ID_TYPE_NITF_FILE_TITLE     AltIDType = 4
	AltIDType_ALT_ID_TYPE_TRACK_REPO_ALERT_ID AltIDType = 5
	AltIDType_ALT_ID_TYPE_ASSET_ID            AltIDType = 6
	AltIDType_ALT_ID_TYPE_LINK16_TRACK_NUMBER AltIDType = 7
	AltIDType_ALT_ID_TYPE_LINK16_JU           AltIDType = 8
	AltIDType_ALT_ID_TYPE_NCCT_MESSAGE_ID     AltIDType = 9
	AltIDType_ALT_ID_TYPE_CALLSIGN            AltIDType = 10
	AltIDType_ALT_ID_TYPE_MMSI_ID             AltIDType = 11
	AltIDType_ALT_ID_TYPE_VMF_URN             AltIDType = 12
	AltIDType_ALT_ID_TYPE_IMO_ID              AltIDType = 13
	AltIDType_ALT_ID_TYPE_VMF_TARGET_NUMBER   AltIDType = 14
	AltIDType_ALT_ID_TYPE_SERIAL_NUMBER       AltIDType = 15
	AltIDType_ALT_ID_TYPE_REGISTRATION_ID     AltIDType = 16
	AltIDType_ALT_ID_TYPE_IBS_GID             AltIDType = 17
	AltIDType_ALT_ID_TYPE_DODAAC              AltIDType = 18
	AltIDType_ALT_ID_TYPE_UIC                 AltIDType = 19
	AltIDType_ALT_ID_TYPE_NORAD_CAT_ID        AltIDType = 20
	AltIDType_ALT_ID_TYPE_UNOOSA_NAME         AltIDType = 21
	AltIDType_ALT_ID_TYPE_UNOOSA_ID           AltIDType = 22
)

// Enum value maps for AltIDType.
var (
	AltIDType_name = map[int32]string{
		0:  "ALT_ID_TYPE_INVALID",
		1:  "ALT_ID_TYPE_TRACK_ID_2",
		2:  "ALT_ID_TYPE_TRACK_ID_1",
		3:  "ALT_ID_TYPE_SPI_ID",
		4:  "ALT_ID_TYPE_NITF_FILE_TITLE",
		5:  "ALT_ID_TYPE_TRACK_REPO_ALERT_ID",
		6:  "ALT_ID_TYPE_ASSET_ID",
		7:  "ALT_ID_TYPE_LINK16_TRACK_NUMBER",
		8:  "ALT_ID_TYPE_LINK16_JU",
		9:  "ALT_ID_TYPE_NCCT_MESSAGE_ID",
		10: "ALT_ID_TYPE_CALLSIGN",
		11: "ALT_ID_TYPE_MMSI_ID",
		12: "ALT_ID_TYPE_VMF_URN",
		13: "ALT_ID_TYPE_IMO_ID",
		14: "ALT_ID_TYPE_VMF_TARGET_NUMBER",
		15: "ALT_ID_TYPE_SERIAL_NUMBER",
		16: "ALT_ID_TYPE_REGISTRATION_ID",
		17: "ALT_ID_TYPE_IBS_GID",
		18: "ALT_ID_TYPE_DODAAC",
		19: "ALT_ID_TYPE_UIC",
		20: "ALT_ID_TYPE_NORAD_CAT_ID",
		21: "ALT_ID_TYPE_UNOOSA_NAME",
		22: "ALT_ID_TYPE_UNOOSA_ID",
	}
	AltIDType_value = map[string]int32{
		"ALT_ID_TYPE_INVALID":             0,
		"ALT_ID_TYPE_TRACK_ID_2":          1,
		"ALT_ID_TYPE_TRACK_ID_1":          2,
		"ALT_ID_TYPE_SPI_ID":              3,
		"ALT_ID_TYPE_NITF_FILE_TITLE":     4,
		"ALT_ID_TYPE_TRACK_REPO_ALERT_ID": 5,
		"ALT_ID_TYPE_ASSET_ID":            6,
		"ALT_ID_TYPE_LINK16_TRACK_NUMBER": 7,
		"ALT_ID_TYPE_LINK16_JU":           8,
		"ALT_ID_TYPE_NCCT_MESSAGE_ID":     9,
		"ALT_ID_TYPE_CALLSIGN":            10,
		"ALT_ID_TYPE_MMSI_ID":             11,
		"ALT_ID_TYPE_VMF_URN":             12,
		"ALT_ID_TYPE_IMO_ID":              13,
		"ALT_ID_TYPE_VMF_TARGET_NUMBER":   14,
		"ALT_ID_TYPE_SERIAL_NUMBER":       15,
		"ALT_ID_TYPE_REGISTRATION_ID":     16,
		"ALT_ID_TYPE_IBS_GID":             17,
		"ALT_ID_TYPE_DODAAC":              18,
		"ALT_ID_TYPE_UIC":                 19,
		"ALT_ID_TYPE_NORAD_CAT_ID":        20,
		"ALT_ID_TYPE_UNOOSA_NAME":         21,
		"ALT_ID_TYPE_UNOOSA_ID":           22,
	}
)

func (x AltIDType) Enum() *AltIDType {
	p := new(AltIDType)
	*p = x
	return p
}

func (x AltIDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AltIDType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_aliases_proto_enumTypes[0].Descriptor()
}

func (AltIDType) Type() protoreflect.EnumType {
	return &file_components_aliases_proto_enumTypes[0]
}

func (x AltIDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AltIDType.Descriptor instead.
func (AltIDType) EnumDescriptor() ([]byte, []int) {
	return file_components_aliases_proto_rawDescGZIP(), []int{0}
}

// Message for AlternateIds
type AlternateIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Type          *AltIDType             `protobuf:"varint,2,opt,name=type,proto3,enum=components.AltIDType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlternateIds) Reset() {
	*x = AlternateIds{}
	mi := &file_components_aliases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlternateIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlternateIds) ProtoMessage() {}

func (x *AlternateIds) ProtoReflect() protoreflect.Message {
	mi := &file_components_aliases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlternateIds.ProtoReflect.Descriptor instead.
func (*AlternateIds) Descriptor() ([]byte, []int) {
	return file_components_aliases_proto_rawDescGZIP(), []int{0}
}

func (x *AlternateIds) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *AlternateIds) GetType() AltIDType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AltIDType_ALT_ID_TYPE_INVALID
}

// Message for Aliases
type Aliases struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlternateIds  []*AlternateIds        `protobuf:"bytes,1,rep,name=alternateIds,proto3" json:"alternateIds,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aliases) Reset() {
	*x = Aliases{}
	mi := &file_components_aliases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aliases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aliases) ProtoMessage() {}

func (x *Aliases) ProtoReflect() protoreflect.Message {
	mi := &file_components_aliases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aliases.ProtoReflect.Descriptor instead.
func (*Aliases) Descriptor() ([]byte, []int) {
	return file_components_aliases_proto_rawDescGZIP(), []int{1}
}

func (x *Aliases) GetAlternateIds() []*AlternateIds {
	if x != nil {
		return x.AlternateIds
	}
	return nil
}

func (x *Aliases) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_components_aliases_proto protoreflect.FileDescriptor

const file_components_aliases_proto_rawDesc = "" +
	"\n" +
	"\x18components/aliases.proto\x12\n" +
	"components\"c\n" +
	"\fAlternateIds\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.components.AltIDTypeH\x01R\x04type\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_type\"i\n" +
	"\aAliases\x12<\n" +
	"\falternateIds\x18\x01 \x03(\v2\x18.components.AlternateIdsR\falternateIds\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name*\x98\x05\n" +
	"\tAltIDType\x12\x17\n" +
	"\x13ALT_ID_TYPE_INVALID\x10\x00\x12\x1a\n" +
	"\x16ALT_ID_TYPE_TRACK_ID_2\x10\x01\x12\x1a\n" +
	"\x16ALT_ID_TYPE_TRACK_ID_1\x10\x02\x12\x16\n" +
	"\x12ALT_ID_TYPE_SPI_ID\x10\x03\x12\x1f\n" +
	"\x1bALT_ID_TYPE_NITF_FILE_TITLE\x10\x04\x12#\n" +
	"\x1fALT_ID_TYPE_TRACK_REPO_ALERT_ID\x10\x05\x12\x18\n" +
	"\x14ALT_ID_TYPE_ASSET_ID\x10\x06\x12#\n" +
	"\x1fALT_ID_TYPE_LINK16_TRACK_NUMBER\x10\a\x12\x19\n" +
	"\x15ALT_ID_TYPE_LINK16_JU\x10\b\x12\x1f\n" +
	"\x1bALT_ID_TYPE_NCCT_MESSAGE_ID\x10\t\x12\x18\n" +
	"\x14ALT_ID_TYPE_CALLSIGN\x10\n" +
	"\x12\x17\n" +
	"\x13ALT_ID_TYPE_MMSI_ID\x10\v\x12\x17\n" +
	"\x13ALT_ID_TYPE_VMF_URN\x10\f\x12\x16\n" +
	"\x12ALT_ID_TYPE_IMO_ID\x10\r\x12!\n" +
	"\x1dALT_ID_TYPE_VMF_TARGET_NUMBER\x10\x0e\x12\x1d\n" +
	"\x19ALT_ID_TYPE_SERIAL_NUMBER\x10\x0f\x12\x1f\n" +
	"\x1bALT_ID_TYPE_REGISTRATION_ID\x10\x10\x12\x17\n" +
	"\x13ALT_ID_TYPE_IBS_GID\x10\x11\x12\x16\n" +
	"\x12ALT_ID_TYPE_DODAAC\x10\x12\x12\x13\n" +
	"\x0fALT_ID_TYPE_UIC\x10\x13\x12\x1c\n" +
	"\x18ALT_ID_TYPE_NORAD_CAT_ID\x10\x14\x12\x1b\n" +
	"\x17ALT_ID_TYPE_UNOOSA_NAME\x10\x15\x12\x19\n" +
	"\x15ALT_ID_TYPE_UNOOSA_ID\x10\x16B\rZ\v/componentsb\x06proto3"

var (
	file_components_aliases_proto_rawDescOnce sync.Once
	file_components_aliases_proto_rawDescData []byte
)

func file_components_aliases_proto_rawDescGZIP() []byte {
	file_components_aliases_proto_rawDescOnce.Do(func() {
		file_components_aliases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_aliases_proto_rawDesc), len(file_components_aliases_proto_rawDesc)))
	})
	return file_components_aliases_proto_rawDescData
}

var file_components_aliases_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_aliases_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_aliases_proto_goTypes = []any{
	(AltIDType)(0),       // 0: components.AltIDType
	(*AlternateIds)(nil), // 1: components.AlternateIds
	(*Aliases)(nil),      // 2: components.Aliases
}
var file_components_aliases_proto_depIdxs = []int32{
	0, // 0: components.AlternateIds.type:type_name -> components.AltIDType
	1, // 1: components.Aliases.alternateIds:type_name -> components.AlternateIds
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_components_aliases_proto_init() }
func file_components_aliases_proto_init() {
	if File_components_aliases_proto != nil {
		return
	}
	file_components_aliases_proto_msgTypes[0].OneofWrappers = []any{}
	file_components_aliases_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_aliases_proto_rawDesc), len(file_components_aliases_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_aliases_proto_goTypes,
		DependencyIndexes: file_components_aliases_proto_depIdxs,
		EnumInfos:         file_components_aliases_proto_enumTypes,
		MessageInfos:      file_components_aliases_proto_msgTypes,
	}.Build()
	File_components_aliases_proto = out.File
	file_components_aliases_proto_goTypes = nil
	file_components_aliases_proto_depIdxs = nil
}
