// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/entity_manager.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEntityRequest) Reset() {
	*x = PublishEntityRequest{}
	mi := &file_components_entity_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEntityRequest) ProtoMessage() {}

func (x *PublishEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEntityRequest.ProtoReflect.Descriptor instead.
func (*PublishEntityRequest) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{0}
}

func (x *PublishEntityRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type PublishEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEntityResponse) Reset() {
	*x = PublishEntityResponse{}
	mi := &file_components_entity_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEntityResponse) ProtoMessage() {}

func (x *PublishEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEntityResponse.ProtoReflect.Descriptor instead.
func (*PublishEntityResponse) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishEntityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEntitiesRequest) Reset() {
	*x = PublishEntitiesRequest{}
	mi := &file_components_entity_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEntitiesRequest) ProtoMessage() {}

func (x *PublishEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEntitiesRequest.ProtoReflect.Descriptor instead.
func (*PublishEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{2}
}

func (x *PublishEntitiesRequest) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type PublishEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEntitiesResponse) Reset() {
	*x = PublishEntitiesResponse{}
	mi := &file_components_entity_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEntitiesResponse) ProtoMessage() {}

func (x *PublishEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEntitiesResponse.ProtoReflect.Descriptor instead.
func (*PublishEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{3}
}

func (x *PublishEntitiesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishEntitiesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_components_entity_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_components_entity_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type OverrideEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	FieldPath     []string               `protobuf:"bytes,2,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Provenance    *Provenance            `protobuf:"bytes,3,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideEntityRequest) Reset() {
	*x = OverrideEntityRequest{}
	mi := &file_components_entity_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideEntityRequest) ProtoMessage() {}

func (x *OverrideEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideEntityRequest.ProtoReflect.Descriptor instead.
func (*OverrideEntityRequest) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{6}
}

func (x *OverrideEntityRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *OverrideEntityRequest) GetFieldPath() []string {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *OverrideEntityRequest) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type OverrideEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OverrideStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=components.OverrideStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideEntityResponse) Reset() {
	*x = OverrideEntityResponse{}
	mi := &file_components_entity_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideEntityResponse) ProtoMessage() {}

func (x *OverrideEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideEntityResponse.ProtoReflect.Descriptor instead.
func (*OverrideEntityResponse) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{7}
}

func (x *OverrideEntityResponse) GetStatus() OverrideStatus {
	if x != nil {
		return x.Status
	}
	return OverrideStatus_OVERRIDE_STATUS_INVALID
}

type RemoveEntityOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	FieldPath     []string               `protobuf:"bytes,2,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityOverrideRequest) Reset() {
	*x = RemoveEntityOverrideRequest{}
	mi := &file_components_entity_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityOverrideRequest) ProtoMessage() {}

func (x *RemoveEntityOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityOverrideRequest.ProtoReflect.Descriptor instead.
func (*RemoveEntityOverrideRequest) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveEntityOverrideRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *RemoveEntityOverrideRequest) GetFieldPath() []string {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

type RemoveEntityOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityOverrideResponse) Reset() {
	*x = RemoveEntityOverrideResponse{}
	mi := &file_components_entity_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityOverrideResponse) ProtoMessage() {}

func (x *RemoveEntityOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_components_entity_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityOverrideResponse.ProtoReflect.Descriptor instead.
func (*RemoveEntityOverrideResponse) Descriptor() ([]byte, []int) {
	return file_components_entity_manager_proto_rawDescGZIP(), []int{9}
}

var File_components_entity_manager_proto protoreflect.FileDescriptor

const file_components_entity_manager_proto_rawDesc = "" +
	"\n" +
	"\x1fcomponents/entity_manager.proto\x12\n" +
	"components\x1a\x17components/entity.proto\x1a\x1bcomponents/provenance.proto\x1a\x1acomponents/overrides.proto\"B\n" +
	"\x14PublishEntityRequest\x12*\n" +
	"\x06entity\x18\x01 \x01(\v2\x12.components.EntityR\x06entity\"K\n" +
	"\x15PublishEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x16PublishEntitiesRequest\x12.\n" +
	"\bentities\x18\x01 \x03(\v2\x12.components.EntityR\bentities\"M\n" +
	"\x17PublishEntitiesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10GetEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"?\n" +
	"\x11GetEntityResponse\x12*\n" +
	"\x06entity\x18\x01 \x01(\v2\x12.components.EntityR\x06entity\"\x9a\x01\n" +
	"\x15OverrideEntityRequest\x12*\n" +
	"\x06entity\x18\x01 \x01(\v2\x12.components.EntityR\x06entity\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x03(\tR\tfieldPath\x126\n" +
	"\n" +
	"provenance\x18\x03 \x01(\v2\x16.components.ProvenanceR\n" +
	"provenance\"L\n" +
	"\x16OverrideEntityResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.components.OverrideStatusR\x06status\"h\n" +
	"\x1bRemoveEntityOverrideRequest\x12*\n" +
	"\x06entity\x18\x01 \x01(\v2\x12.components.EntityR\x06entity\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x03(\tR\tfieldPath\"\x1e\n" +
	"\x1cRemoveEntityOverrideResponse2\xcd\x03\n" +
	"\rEntityManager\x12T\n" +
	"\rPublishEntity\x12 .components.PublishEntityRequest\x1a!.components.PublishEntityResponse\x12X\n" +
	"\x0fPublishEntities\x12 .components.PublishEntityRequest\x1a#.components.PublishEntitiesResponse\x12H\n" +
	"\tGetEntity\x12\x1c.components.GetEntityRequest\x1a\x1d.components.GetEntityResponse\x12W\n" +
	"\x0eOverrideEntity\x12!.components.OverrideEntityRequest\x1a\".components.OverrideEntityResponse\x12i\n" +
	"\x14RemoveEntityOverride\x12'.components.RemoveEntityOverrideRequest\x1a(.components.RemoveEntityOverrideResponseB\rZ\v/componentsb\x06proto3"

var (
	file_components_entity_manager_proto_rawDescOnce sync.Once
	file_components_entity_manager_proto_rawDescData []byte
)

func file_components_entity_manager_proto_rawDescGZIP() []byte {
	file_components_entity_manager_proto_rawDescOnce.Do(func() {
		file_components_entity_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_entity_manager_proto_rawDesc), len(file_components_entity_manager_proto_rawDesc)))
	})
	return file_components_entity_manager_proto_rawDescData
}

var file_components_entity_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_components_entity_manager_proto_goTypes = []any{
	(*PublishEntityRequest)(nil),         // 0: components.PublishEntityRequest
	(*PublishEntityResponse)(nil),        // 1: components.PublishEntityResponse
	(*PublishEntitiesRequest)(nil),       // 2: components.PublishEntitiesRequest
	(*PublishEntitiesResponse)(nil),      // 3: components.PublishEntitiesResponse
	(*GetEntityRequest)(nil),             // 4: components.GetEntityRequest
	(*GetEntityResponse)(nil),            // 5: components.GetEntityResponse
	(*OverrideEntityRequest)(nil),        // 6: components.OverrideEntityRequest
	(*OverrideEntityResponse)(nil),       // 7: components.OverrideEntityResponse
	(*RemoveEntityOverrideRequest)(nil),  // 8: components.RemoveEntityOverrideRequest
	(*RemoveEntityOverrideResponse)(nil), // 9: components.RemoveEntityOverrideResponse
	(*Entity)(nil),                       // 10: components.Entity
	(*Provenance)(nil),                   // 11: components.Provenance
	(OverrideStatus)(0),                  // 12: components.OverrideStatus
}
var file_components_entity_manager_proto_depIdxs = []int32{
	10, // 0: components.PublishEntityRequest.entity:type_name -> components.Entity
	10, // 1: components.PublishEntitiesRequest.entities:type_name -> components.Entity
	10, // 2: components.GetEntityResponse.entity:type_name -> components.Entity
	10, // 3: components.OverrideEntityRequest.entity:type_name -> components.Entity
	11, // 4: components.OverrideEntityRequest.provenance:type_name -> components.Provenance
	12, // 5: components.OverrideEntityResponse.status:type_name -> components.OverrideStatus
	10, // 6: components.RemoveEntityOverrideRequest.entity:type_name -> components.Entity
	0,  // 7: components.EntityManager.PublishEntity:input_type -> components.PublishEntityRequest
	0,  // 8: components.EntityManager.PublishEntities:input_type -> components.PublishEntityRequest
	4,  // 9: components.EntityManager.GetEntity:input_type -> components.GetEntityRequest
	6,  // 10: components.EntityManager.OverrideEntity:input_type -> components.OverrideEntityRequest
	8,  // 11: components.EntityManager.RemoveEntityOverride:input_type -> components.RemoveEntityOverrideRequest
	1,  // 12: components.EntityManager.PublishEntity:output_type -> components.PublishEntityResponse
	3,  // 13: components.EntityManager.PublishEntities:output_type -> components.PublishEntitiesResponse
	5,  // 14: components.EntityManager.GetEntity:output_type -> components.GetEntityResponse
	7,  // 15: components.EntityManager.OverrideEntity:output_type -> components.OverrideEntityResponse
	9,  // 16: components.EntityManager.RemoveEntityOverride:output_type -> components.RemoveEntityOverrideResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_components_entity_manager_proto_init() }
func file_components_entity_manager_proto_init() {
	if File_components_entity_manager_proto != nil {
		return
	}
	file_components_entity_proto_init()
	file_components_provenance_proto_init()
	file_components_overrides_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_entity_manager_proto_rawDesc), len(file_components_entity_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_components_entity_manager_proto_goTypes,
		DependencyIndexes: file_components_entity_manager_proto_depIdxs,
		MessageInfos:      file_components_entity_manager_proto_msgTypes,
	}.Build()
	File_components_entity_manager_proto = out.File
	file_components_entity_manager_proto_goTypes = nil
	file_components_entity_manager_proto_depIdxs = nil
}
