// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/location_uncertainty.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationUncertainty struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PositionEnuCov       *PositionEnuCov        `protobuf:"bytes,1,opt,name=positionEnuCov,proto3,oneof" json:"positionEnuCov,omitempty"`
	VelocityEnuCov       *VelocityEnuCov        `protobuf:"bytes,2,opt,name=velocityEnuCov,proto3,oneof" json:"velocityEnuCov,omitempty"`
	PositionErrorEllipse *PositionErrorEllipse  `protobuf:"bytes,3,opt,name=positionErrorEllipse,proto3,oneof" json:"positionErrorEllipse,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LocationUncertainty) Reset() {
	*x = LocationUncertainty{}
	mi := &file_components_location_uncertainty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUncertainty) ProtoMessage() {}

func (x *LocationUncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUncertainty.ProtoReflect.Descriptor instead.
func (*LocationUncertainty) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{0}
}

func (x *LocationUncertainty) GetPositionEnuCov() *PositionEnuCov {
	if x != nil {
		return x.PositionEnuCov
	}
	return nil
}

func (x *LocationUncertainty) GetVelocityEnuCov() *VelocityEnuCov {
	if x != nil {
		return x.VelocityEnuCov
	}
	return nil
}

func (x *LocationUncertainty) GetPositionErrorEllipse() *PositionErrorEllipse {
	if x != nil {
		return x.PositionErrorEllipse
	}
	return nil
}

type PositionEnuCov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mxx           *float32               `protobuf:"fixed32,1,opt,name=mxx,proto3,oneof" json:"mxx,omitempty"`
	Mxy           *float32               `protobuf:"fixed32,2,opt,name=mxy,proto3,oneof" json:"mxy,omitempty"`
	Mxz           *float32               `protobuf:"fixed32,3,opt,name=mxz,proto3,oneof" json:"mxz,omitempty"`
	Myy           *float32               `protobuf:"fixed32,4,opt,name=myy,proto3,oneof" json:"myy,omitempty"`
	Myz           *float32               `protobuf:"fixed32,5,opt,name=myz,proto3,oneof" json:"myz,omitempty"`
	Mzz           *float32               `protobuf:"fixed32,6,opt,name=mzz,proto3,oneof" json:"mzz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionEnuCov) Reset() {
	*x = PositionEnuCov{}
	mi := &file_components_location_uncertainty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionEnuCov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionEnuCov) ProtoMessage() {}

func (x *PositionEnuCov) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionEnuCov.ProtoReflect.Descriptor instead.
func (*PositionEnuCov) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{1}
}

func (x *PositionEnuCov) GetMxx() float32 {
	if x != nil && x.Mxx != nil {
		return *x.Mxx
	}
	return 0
}

func (x *PositionEnuCov) GetMxy() float32 {
	if x != nil && x.Mxy != nil {
		return *x.Mxy
	}
	return 0
}

func (x *PositionEnuCov) GetMxz() float32 {
	if x != nil && x.Mxz != nil {
		return *x.Mxz
	}
	return 0
}

func (x *PositionEnuCov) GetMyy() float32 {
	if x != nil && x.Myy != nil {
		return *x.Myy
	}
	return 0
}

func (x *PositionEnuCov) GetMyz() float32 {
	if x != nil && x.Myz != nil {
		return *x.Myz
	}
	return 0
}

func (x *PositionEnuCov) GetMzz() float32 {
	if x != nil && x.Mzz != nil {
		return *x.Mzz
	}
	return 0
}

type VelocityEnuCov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mxx           *float32               `protobuf:"fixed32,1,opt,name=mxx,proto3,oneof" json:"mxx,omitempty"`
	Mxy           *float32               `protobuf:"fixed32,2,opt,name=mxy,proto3,oneof" json:"mxy,omitempty"`
	Mxz           *float32               `protobuf:"fixed32,3,opt,name=mxz,proto3,oneof" json:"mxz,omitempty"`
	Myy           *float32               `protobuf:"fixed32,4,opt,name=myy,proto3,oneof" json:"myy,omitempty"`
	Myz           *float32               `protobuf:"fixed32,5,opt,name=myz,proto3,oneof" json:"myz,omitempty"`
	Mzz           *float32               `protobuf:"fixed32,6,opt,name=mzz,proto3,oneof" json:"mzz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VelocityEnuCov) Reset() {
	*x = VelocityEnuCov{}
	mi := &file_components_location_uncertainty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VelocityEnuCov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VelocityEnuCov) ProtoMessage() {}

func (x *VelocityEnuCov) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VelocityEnuCov.ProtoReflect.Descriptor instead.
func (*VelocityEnuCov) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{2}
}

func (x *VelocityEnuCov) GetMxx() float32 {
	if x != nil && x.Mxx != nil {
		return *x.Mxx
	}
	return 0
}

func (x *VelocityEnuCov) GetMxy() float32 {
	if x != nil && x.Mxy != nil {
		return *x.Mxy
	}
	return 0
}

func (x *VelocityEnuCov) GetMxz() float32 {
	if x != nil && x.Mxz != nil {
		return *x.Mxz
	}
	return 0
}

func (x *VelocityEnuCov) GetMyy() float32 {
	if x != nil && x.Myy != nil {
		return *x.Myy
	}
	return 0
}

func (x *VelocityEnuCov) GetMyz() float32 {
	if x != nil && x.Myz != nil {
		return *x.Myz
	}
	return 0
}

func (x *VelocityEnuCov) GetMzz() float32 {
	if x != nil && x.Mzz != nil {
		return *x.Mzz
	}
	return 0
}

type PositionErrorEllipse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Probability    *float64               `protobuf:"fixed64,1,opt,name=probability,proto3,oneof" json:"probability,omitempty"`
	SemiMajorAxisM *float64               `protobuf:"fixed64,2,opt,name=semiMajorAxisM,proto3,oneof" json:"semiMajorAxisM,omitempty"`
	SemiMinorAxisM *float64               `protobuf:"fixed64,3,opt,name=semiMinorAxisM,proto3,oneof" json:"semiMinorAxisM,omitempty"`
	OrientationD   *float64               `protobuf:"fixed64,4,opt,name=orientationD,proto3,oneof" json:"orientationD,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PositionErrorEllipse) Reset() {
	*x = PositionErrorEllipse{}
	mi := &file_components_location_uncertainty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionErrorEllipse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionErrorEllipse) ProtoMessage() {}

func (x *PositionErrorEllipse) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_uncertainty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionErrorEllipse.ProtoReflect.Descriptor instead.
func (*PositionErrorEllipse) Descriptor() ([]byte, []int) {
	return file_components_location_uncertainty_proto_rawDescGZIP(), []int{3}
}

func (x *PositionErrorEllipse) GetProbability() float64 {
	if x != nil && x.Probability != nil {
		return *x.Probability
	}
	return 0
}

func (x *PositionErrorEllipse) GetSemiMajorAxisM() float64 {
	if x != nil && x.SemiMajorAxisM != nil {
		return *x.SemiMajorAxisM
	}
	return 0
}

func (x *PositionErrorEllipse) GetSemiMinorAxisM() float64 {
	if x != nil && x.SemiMinorAxisM != nil {
		return *x.SemiMinorAxisM
	}
	return 0
}

func (x *PositionErrorEllipse) GetOrientationD() float64 {
	if x != nil && x.OrientationD != nil {
		return *x.OrientationD
	}
	return 0
}

var File_components_location_uncertainty_proto protoreflect.FileDescriptor

const file_components_location_uncertainty_proto_rawDesc = "" +
	"\n" +
	"%components/location_uncertainty.proto\x12\n" +
	"components\"\xc1\x02\n" +
	"\x13LocationUncertainty\x12G\n" +
	"\x0epositionEnuCov\x18\x01 \x01(\v2\x1a.components.PositionEnuCovH\x00R\x0epositionEnuCov\x88\x01\x01\x12G\n" +
	"\x0evelocityEnuCov\x18\x02 \x01(\v2\x1a.components.VelocityEnuCovH\x01R\x0evelocityEnuCov\x88\x01\x01\x12Y\n" +
	"\x14positionErrorEllipse\x18\x03 \x01(\v2 .components.PositionErrorEllipseH\x02R\x14positionErrorEllipse\x88\x01\x01B\x11\n" +
	"\x0f_positionEnuCovB\x11\n" +
	"\x0f_velocityEnuCovB\x17\n" +
	"\x15_positionErrorEllipse\"\xca\x01\n" +
	"\x0ePositionEnuCov\x12\x15\n" +
	"\x03mxx\x18\x01 \x01(\x02H\x00R\x03mxx\x88\x01\x01\x12\x15\n" +
	"\x03mxy\x18\x02 \x01(\x02H\x01R\x03mxy\x88\x01\x01\x12\x15\n" +
	"\x03mxz\x18\x03 \x01(\x02H\x02R\x03mxz\x88\x01\x01\x12\x15\n" +
	"\x03myy\x18\x04 \x01(\x02H\x03R\x03myy\x88\x01\x01\x12\x15\n" +
	"\x03myz\x18\x05 \x01(\x02H\x04R\x03myz\x88\x01\x01\x12\x15\n" +
	"\x03mzz\x18\x06 \x01(\x02H\x05R\x03mzz\x88\x01\x01B\x06\n" +
	"\x04_mxxB\x06\n" +
	"\x04_mxyB\x06\n" +
	"\x04_mxzB\x06\n" +
	"\x04_myyB\x06\n" +
	"\x04_myzB\x06\n" +
	"\x04_mzz\"\xca\x01\n" +
	"\x0eVelocityEnuCov\x12\x15\n" +
	"\x03mxx\x18\x01 \x01(\x02H\x00R\x03mxx\x88\x01\x01\x12\x15\n" +
	"\x03mxy\x18\x02 \x01(\x02H\x01R\x03mxy\x88\x01\x01\x12\x15\n" +
	"\x03mxz\x18\x03 \x01(\x02H\x02R\x03mxz\x88\x01\x01\x12\x15\n" +
	"\x03myy\x18\x04 \x01(\x02H\x03R\x03myy\x88\x01\x01\x12\x15\n" +
	"\x03myz\x18\x05 \x01(\x02H\x04R\x03myz\x88\x01\x01\x12\x15\n" +
	"\x03mzz\x18\x06 \x01(\x02H\x05R\x03mzz\x88\x01\x01B\x06\n" +
	"\x04_mxxB\x06\n" +
	"\x04_mxyB\x06\n" +
	"\x04_mxzB\x06\n" +
	"\x04_myyB\x06\n" +
	"\x04_myzB\x06\n" +
	"\x04_mzz\"\x87\x02\n" +
	"\x14PositionErrorEllipse\x12%\n" +
	"\vprobability\x18\x01 \x01(\x01H\x00R\vprobability\x88\x01\x01\x12+\n" +
	"\x0esemiMajorAxisM\x18\x02 \x01(\x01H\x01R\x0esemiMajorAxisM\x88\x01\x01\x12+\n" +
	"\x0esemiMinorAxisM\x18\x03 \x01(\x01H\x02R\x0esemiMinorAxisM\x88\x01\x01\x12'\n" +
	"\forientationD\x18\x04 \x01(\x01H\x03R\forientationD\x88\x01\x01B\x0e\n" +
	"\f_probabilityB\x11\n" +
	"\x0f_semiMajorAxisMB\x11\n" +
	"\x0f_semiMinorAxisMB\x0f\n" +
	"\r_orientationDB\rZ\v/componentsb\x06proto3"

var (
	file_components_location_uncertainty_proto_rawDescOnce sync.Once
	file_components_location_uncertainty_proto_rawDescData []byte
)

func file_components_location_uncertainty_proto_rawDescGZIP() []byte {
	file_components_location_uncertainty_proto_rawDescOnce.Do(func() {
		file_components_location_uncertainty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_location_uncertainty_proto_rawDesc), len(file_components_location_uncertainty_proto_rawDesc)))
	})
	return file_components_location_uncertainty_proto_rawDescData
}

var file_components_location_uncertainty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_location_uncertainty_proto_goTypes = []any{
	(*LocationUncertainty)(nil),  // 0: components.LocationUncertainty
	(*PositionEnuCov)(nil),       // 1: components.PositionEnuCov
	(*VelocityEnuCov)(nil),       // 2: components.VelocityEnuCov
	(*PositionErrorEllipse)(nil), // 3: components.PositionErrorEllipse
}
var file_components_location_uncertainty_proto_depIdxs = []int32{
	1, // 0: components.LocationUncertainty.positionEnuCov:type_name -> components.PositionEnuCov
	2, // 1: components.LocationUncertainty.velocityEnuCov:type_name -> components.VelocityEnuCov
	3, // 2: components.LocationUncertainty.positionErrorEllipse:type_name -> components.PositionErrorEllipse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_location_uncertainty_proto_init() }
func file_components_location_uncertainty_proto_init() {
	if File_components_location_uncertainty_proto != nil {
		return
	}
	file_components_location_uncertainty_proto_msgTypes[0].OneofWrappers = []any{}
	file_components_location_uncertainty_proto_msgTypes[1].OneofWrappers = []any{}
	file_components_location_uncertainty_proto_msgTypes[2].OneofWrappers = []any{}
	file_components_location_uncertainty_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_location_uncertainty_proto_rawDesc), len(file_components_location_uncertainty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_location_uncertainty_proto_goTypes,
		DependencyIndexes: file_components_location_uncertainty_proto_depIdxs,
		MessageInfos:      file_components_location_uncertainty_proto_msgTypes,
	}.Build()
	File_components_location_uncertainty_proto = out.File
	file_components_location_uncertainty_proto_goTypes = nil
	file_components_location_uncertainty_proto_depIdxs = nil
}
