// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/location.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3,oneof" json:"position,omitempty"`
	VelocityEnu   *VelocityEnu           `protobuf:"bytes,2,opt,name=velocityEnu,proto3,oneof" json:"velocityEnu,omitempty"`
	SpeedMps      *float64               `protobuf:"fixed64,3,opt,name=speedMps,proto3,oneof" json:"speedMps,omitempty"`
	Acceleration  *Acceleration          `protobuf:"bytes,4,opt,name=acceleration,proto3,oneof" json:"acceleration,omitempty"`
	AttitudeEnu   *AttitudeEnu           `protobuf:"bytes,5,opt,name=attitudeEnu,proto3,oneof" json:"attitudeEnu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_components_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_components_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Location) GetVelocityEnu() *VelocityEnu {
	if x != nil {
		return x.VelocityEnu
	}
	return nil
}

func (x *Location) GetSpeedMps() float64 {
	if x != nil && x.SpeedMps != nil {
		return *x.SpeedMps
	}
	return 0
}

func (x *Location) GetAcceleration() *Acceleration {
	if x != nil {
		return x.Acceleration
	}
	return nil
}

func (x *Location) GetAttitudeEnu() *AttitudeEnu {
	if x != nil {
		return x.AttitudeEnu
	}
	return nil
}

type VelocityEnu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E             *float64               `protobuf:"fixed64,1,opt,name=e,proto3,oneof" json:"e,omitempty"`
	N             *float64               `protobuf:"fixed64,2,opt,name=n,proto3,oneof" json:"n,omitempty"`
	U             *float64               `protobuf:"fixed64,3,opt,name=u,proto3,oneof" json:"u,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VelocityEnu) Reset() {
	*x = VelocityEnu{}
	mi := &file_components_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VelocityEnu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VelocityEnu) ProtoMessage() {}

func (x *VelocityEnu) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VelocityEnu.ProtoReflect.Descriptor instead.
func (*VelocityEnu) Descriptor() ([]byte, []int) {
	return file_components_location_proto_rawDescGZIP(), []int{1}
}

func (x *VelocityEnu) GetE() float64 {
	if x != nil && x.E != nil {
		return *x.E
	}
	return 0
}

func (x *VelocityEnu) GetN() float64 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *VelocityEnu) GetU() float64 {
	if x != nil && x.U != nil {
		return *x.U
	}
	return 0
}

type Acceleration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E             *float64               `protobuf:"fixed64,1,opt,name=e,proto3,oneof" json:"e,omitempty"`
	N             *float64               `protobuf:"fixed64,2,opt,name=n,proto3,oneof" json:"n,omitempty"`
	U             *float64               `protobuf:"fixed64,3,opt,name=u,proto3,oneof" json:"u,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acceleration) Reset() {
	*x = Acceleration{}
	mi := &file_components_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acceleration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acceleration) ProtoMessage() {}

func (x *Acceleration) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acceleration.ProtoReflect.Descriptor instead.
func (*Acceleration) Descriptor() ([]byte, []int) {
	return file_components_location_proto_rawDescGZIP(), []int{2}
}

func (x *Acceleration) GetE() float64 {
	if x != nil && x.E != nil {
		return *x.E
	}
	return 0
}

func (x *Acceleration) GetN() float64 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *Acceleration) GetU() float64 {
	if x != nil && x.U != nil {
		return *x.U
	}
	return 0
}

type AttitudeEnu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float64               `protobuf:"fixed64,1,opt,name=x,proto3,oneof" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,2,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Z             *float64               `protobuf:"fixed64,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
	W             *float64               `protobuf:"fixed64,4,opt,name=w,proto3,oneof" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttitudeEnu) Reset() {
	*x = AttitudeEnu{}
	mi := &file_components_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttitudeEnu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttitudeEnu) ProtoMessage() {}

func (x *AttitudeEnu) ProtoReflect() protoreflect.Message {
	mi := &file_components_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttitudeEnu.ProtoReflect.Descriptor instead.
func (*AttitudeEnu) Descriptor() ([]byte, []int) {
	return file_components_location_proto_rawDescGZIP(), []int{3}
}

func (x *AttitudeEnu) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *AttitudeEnu) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *AttitudeEnu) GetZ() float64 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *AttitudeEnu) GetW() float64 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

var File_components_location_proto protoreflect.FileDescriptor

const file_components_location_proto_rawDesc = "" +
	"\n" +
	"\x19components/location.proto\x12\n" +
	"components\x1a\x19components/position.proto\"\xf0\x02\n" +
	"\bLocation\x125\n" +
	"\bposition\x18\x01 \x01(\v2\x14.components.PositionH\x00R\bposition\x88\x01\x01\x12>\n" +
	"\vvelocityEnu\x18\x02 \x01(\v2\x17.components.VelocityEnuH\x01R\vvelocityEnu\x88\x01\x01\x12\x1f\n" +
	"\bspeedMps\x18\x03 \x01(\x01H\x02R\bspeedMps\x88\x01\x01\x12A\n" +
	"\facceleration\x18\x04 \x01(\v2\x18.components.AccelerationH\x03R\facceleration\x88\x01\x01\x12>\n" +
	"\vattitudeEnu\x18\x05 \x01(\v2\x17.components.AttitudeEnuH\x04R\vattitudeEnu\x88\x01\x01B\v\n" +
	"\t_positionB\x0e\n" +
	"\f_velocityEnuB\v\n" +
	"\t_speedMpsB\x0f\n" +
	"\r_accelerationB\x0e\n" +
	"\f_attitudeEnu\"X\n" +
	"\vVelocityEnu\x12\x11\n" +
	"\x01e\x18\x01 \x01(\x01H\x00R\x01e\x88\x01\x01\x12\x11\n" +
	"\x01n\x18\x02 \x01(\x01H\x01R\x01n\x88\x01\x01\x12\x11\n" +
	"\x01u\x18\x03 \x01(\x01H\x02R\x01u\x88\x01\x01B\x04\n" +
	"\x02_eB\x04\n" +
	"\x02_nB\x04\n" +
	"\x02_u\"Y\n" +
	"\fAcceleration\x12\x11\n" +
	"\x01e\x18\x01 \x01(\x01H\x00R\x01e\x88\x01\x01\x12\x11\n" +
	"\x01n\x18\x02 \x01(\x01H\x01R\x01n\x88\x01\x01\x12\x11\n" +
	"\x01u\x18\x03 \x01(\x01H\x02R\x01u\x88\x01\x01B\x04\n" +
	"\x02_eB\x04\n" +
	"\x02_nB\x04\n" +
	"\x02_u\"q\n" +
	"\vAttitudeEnu\x12\x11\n" +
	"\x01x\x18\x01 \x01(\x01H\x00R\x01x\x88\x01\x01\x12\x11\n" +
	"\x01y\x18\x02 \x01(\x01H\x01R\x01y\x88\x01\x01\x12\x11\n" +
	"\x01z\x18\x03 \x01(\x01H\x02R\x01z\x88\x01\x01\x12\x11\n" +
	"\x01w\x18\x04 \x01(\x01H\x03R\x01w\x88\x01\x01B\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\x04\n" +
	"\x02_zB\x04\n" +
	"\x02_wB\rZ\v/componentsb\x06proto3"

var (
	file_components_location_proto_rawDescOnce sync.Once
	file_components_location_proto_rawDescData []byte
)

func file_components_location_proto_rawDescGZIP() []byte {
	file_components_location_proto_rawDescOnce.Do(func() {
		file_components_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_location_proto_rawDesc), len(file_components_location_proto_rawDesc)))
	})
	return file_components_location_proto_rawDescData
}

var file_components_location_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_location_proto_goTypes = []any{
	(*Location)(nil),     // 0: components.Location
	(*VelocityEnu)(nil),  // 1: components.VelocityEnu
	(*Acceleration)(nil), // 2: components.Acceleration
	(*AttitudeEnu)(nil),  // 3: components.AttitudeEnu
	(*Position)(nil),     // 4: components.Position
}
var file_components_location_proto_depIdxs = []int32{
	4, // 0: components.Location.position:type_name -> components.Position
	1, // 1: components.Location.velocityEnu:type_name -> components.VelocityEnu
	2, // 2: components.Location.acceleration:type_name -> components.Acceleration
	3, // 3: components.Location.attitudeEnu:type_name -> components.AttitudeEnu
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_components_location_proto_init() }
func file_components_location_proto_init() {
	if File_components_location_proto != nil {
		return
	}
	file_components_position_proto_init()
	file_components_location_proto_msgTypes[0].OneofWrappers = []any{}
	file_components_location_proto_msgTypes[1].OneofWrappers = []any{}
	file_components_location_proto_msgTypes[2].OneofWrappers = []any{}
	file_components_location_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_location_proto_rawDesc), len(file_components_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_location_proto_goTypes,
		DependencyIndexes: file_components_location_proto_depIdxs,
		MessageInfos:      file_components_location_proto_msgTypes,
	}.Build()
	File_components_location_proto = out.File
	file_components_location_proto_goTypes = nil
	file_components_location_proto_depIdxs = nil
}
