// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/payloads.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadOperationalState int32

const (
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_INVALID         PayloadOperationalState = 0
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_OFF             PayloadOperationalState = 1
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_NON_OPERATIONAL PayloadOperationalState = 2
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_DEGRADED        PayloadOperationalState = 3
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_OPERATIONAL     PayloadOperationalState = 4
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_OUT_OF_SERVICE  PayloadOperationalState = 5
	PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_UNKNOWN         PayloadOperationalState = 6
)

// Enum value maps for PayloadOperationalState.
var (
	PayloadOperationalState_name = map[int32]string{
		0: "PAYLOAD_OPERATIONAL_STATE_INVALID",
		1: "PAYLOAD_OPERATIONAL_STATE_OFF",
		2: "PAYLOAD_OPERATIONAL_STATE_NON_OPERATIONAL",
		3: "PAYLOAD_OPERATIONAL_STATE_DEGRADED",
		4: "PAYLOAD_OPERATIONAL_STATE_OPERATIONAL",
		5: "PAYLOAD_OPERATIONAL_STATE_OUT_OF_SERVICE",
		6: "PAYLOAD_OPERATIONAL_STATE_UNKNOWN",
	}
	PayloadOperationalState_value = map[string]int32{
		"PAYLOAD_OPERATIONAL_STATE_INVALID":         0,
		"PAYLOAD_OPERATIONAL_STATE_OFF":             1,
		"PAYLOAD_OPERATIONAL_STATE_NON_OPERATIONAL": 2,
		"PAYLOAD_OPERATIONAL_STATE_DEGRADED":        3,
		"PAYLOAD_OPERATIONAL_STATE_OPERATIONAL":     4,
		"PAYLOAD_OPERATIONAL_STATE_OUT_OF_SERVICE":  5,
		"PAYLOAD_OPERATIONAL_STATE_UNKNOWN":         6,
	}
)

func (x PayloadOperationalState) Enum() *PayloadOperationalState {
	p := new(PayloadOperationalState)
	*p = x
	return p
}

func (x PayloadOperationalState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadOperationalState) Descriptor() protoreflect.EnumDescriptor {
	return file_components_payloads_proto_enumTypes[0].Descriptor()
}

func (PayloadOperationalState) Type() protoreflect.EnumType {
	return &file_components_payloads_proto_enumTypes[0]
}

func (x PayloadOperationalState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadOperationalState.Descriptor instead.
func (PayloadOperationalState) EnumDescriptor() ([]byte, []int) {
	return file_components_payloads_proto_rawDescGZIP(), []int{0}
}

type Payloads struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PayloadConfigurations []*Config              `protobuf:"bytes,1,rep,name=payloadConfigurations,proto3" json:"payloadConfigurations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Payloads) Reset() {
	*x = Payloads{}
	mi := &file_components_payloads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payloads) ProtoMessage() {}

func (x *Payloads) ProtoReflect() protoreflect.Message {
	mi := &file_components_payloads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payloads.ProtoReflect.Descriptor instead.
func (*Payloads) Descriptor() ([]byte, []int) {
	return file_components_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *Payloads) GetPayloadConfigurations() []*Config {
	if x != nil {
		return x.PayloadConfigurations
	}
	return nil
}

type Config struct {
	state                   protoimpl.MessageState  `protogen:"open.v1"`
	CapabilityId            string                  `protobuf:"bytes,1,opt,name=capabilityId,proto3" json:"capabilityId,omitempty"`
	Quantity                uint32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EffectiveEnvironment    Environment             `protobuf:"varint,3,opt,name=effectiveEnvironment,proto3,enum=components.Environment" json:"effectiveEnvironment,omitempty"`
	PayloadOperationalState PayloadOperationalState `protobuf:"varint,4,opt,name=payloadOperationalState,proto3,enum=components.PayloadOperationalState" json:"payloadOperationalState,omitempty"`
	PayloadDescription      string                  `protobuf:"bytes,5,opt,name=payloadDescription,proto3" json:"payloadDescription,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_components_payloads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_components_payloads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_components_payloads_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *Config) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Config) GetEffectiveEnvironment() Environment {
	if x != nil {
		return x.EffectiveEnvironment
	}
	return Environment_ENVIRONMENT_UNKNOWN
}

func (x *Config) GetPayloadOperationalState() PayloadOperationalState {
	if x != nil {
		return x.PayloadOperationalState
	}
	return PayloadOperationalState_PAYLOAD_OPERATIONAL_STATE_INVALID
}

func (x *Config) GetPayloadDescription() string {
	if x != nil {
		return x.PayloadDescription
	}
	return ""
}

var File_components_payloads_proto protoreflect.FileDescriptor

const file_components_payloads_proto_rawDesc = "" +
	"\n" +
	"\x19components/payloads.proto\x12\n" +
	"components\x1a\x19components/mil_view.proto\"T\n" +
	"\bPayloads\x12H\n" +
	"\x15payloadConfigurations\x18\x01 \x03(\v2\x12.components.ConfigR\x15payloadConfigurations\"\xa4\x02\n" +
	"\x06Config\x12\"\n" +
	"\fcapabilityId\x18\x01 \x01(\tR\fcapabilityId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12K\n" +
	"\x14effectiveEnvironment\x18\x03 \x01(\x0e2\x17.components.EnvironmentR\x14effectiveEnvironment\x12]\n" +
	"\x17payloadOperationalState\x18\x04 \x01(\x0e2#.components.PayloadOperationalStateR\x17payloadOperationalState\x12.\n" +
	"\x12payloadDescription\x18\x05 \x01(\tR\x12payloadDescription*\xba\x02\n" +
	"\x17PayloadOperationalState\x12%\n" +
	"!PAYLOAD_OPERATIONAL_STATE_INVALID\x10\x00\x12!\n" +
	"\x1dPAYLOAD_OPERATIONAL_STATE_OFF\x10\x01\x12-\n" +
	")PAYLOAD_OPERATIONAL_STATE_NON_OPERATIONAL\x10\x02\x12&\n" +
	"\"PAYLOAD_OPERATIONAL_STATE_DEGRADED\x10\x03\x12)\n" +
	"%PAYLOAD_OPERATIONAL_STATE_OPERATIONAL\x10\x04\x12,\n" +
	"(PAYLOAD_OPERATIONAL_STATE_OUT_OF_SERVICE\x10\x05\x12%\n" +
	"!PAYLOAD_OPERATIONAL_STATE_UNKNOWN\x10\x06B\rZ\v/componentsb\x06proto3"

var (
	file_components_payloads_proto_rawDescOnce sync.Once
	file_components_payloads_proto_rawDescData []byte
)

func file_components_payloads_proto_rawDescGZIP() []byte {
	file_components_payloads_proto_rawDescOnce.Do(func() {
		file_components_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_payloads_proto_rawDesc), len(file_components_payloads_proto_rawDesc)))
	})
	return file_components_payloads_proto_rawDescData
}

var file_components_payloads_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_payloads_proto_goTypes = []any{
	(PayloadOperationalState)(0), // 0: components.PayloadOperationalState
	(*Payloads)(nil),             // 1: components.Payloads
	(*Config)(nil),               // 2: components.Config
	(Environment)(0),             // 3: components.Environment
}
var file_components_payloads_proto_depIdxs = []int32{
	2, // 0: components.Payloads.payloadConfigurations:type_name -> components.Config
	3, // 1: components.Config.effectiveEnvironment:type_name -> components.Environment
	0, // 2: components.Config.payloadOperationalState:type_name -> components.PayloadOperationalState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_payloads_proto_init() }
func file_components_payloads_proto_init() {
	if File_components_payloads_proto != nil {
		return
	}
	file_components_mil_view_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_payloads_proto_rawDesc), len(file_components_payloads_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_payloads_proto_goTypes,
		DependencyIndexes: file_components_payloads_proto_depIdxs,
		EnumInfos:         file_components_payloads_proto_enumTypes,
		MessageInfos:      file_components_payloads_proto_msgTypes,
	}.Build()
	File_components_payloads_proto = out.File
	file_components_payloads_proto_goTypes = nil
	file_components_payloads_proto_depIdxs = nil
}
