// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/relationships.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relationships struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*Relationship        `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationships) Reset() {
	*x = Relationships{}
	mi := &file_components_relationships_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationships) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationships) ProtoMessage() {}

func (x *Relationships) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationships.ProtoReflect.Descriptor instead.
func (*Relationships) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{0}
}

func (x *Relationships) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type Relationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelatedEntityId  *string                `protobuf:"bytes,1,opt,name=relatedEntityId,proto3,oneof" json:"relatedEntityId,omitempty"`
	RelationshipId   *string                `protobuf:"bytes,2,opt,name=relationshipId,proto3,oneof" json:"relationshipId,omitempty"`
	RelationshipType *RelationshipType      `protobuf:"bytes,3,opt,name=relationshipType,proto3,oneof" json:"relationshipType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_components_relationships_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{1}
}

func (x *Relationship) GetRelatedEntityId() string {
	if x != nil && x.RelatedEntityId != nil {
		return *x.RelatedEntityId
	}
	return ""
}

func (x *Relationship) GetRelationshipId() string {
	if x != nil && x.RelationshipId != nil {
		return *x.RelationshipId
	}
	return ""
}

func (x *Relationship) GetRelationshipType() *RelationshipType {
	if x != nil {
		return x.RelationshipType
	}
	return nil
}

type RelationshipType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackedBy     *TrackedBy             `protobuf:"bytes,1,opt,name=trackedBy,proto3,oneof" json:"trackedBy,omitempty"`
	GroupChild    *GroupChild            `protobuf:"bytes,2,opt,name=groupChild,proto3,oneof" json:"groupChild,omitempty"`
	GroupParent   *GroupParent           `protobuf:"bytes,3,opt,name=groupParent,proto3,oneof" json:"groupParent,omitempty"`
	MergedFrom    *MergedFrom            `protobuf:"bytes,4,opt,name=mergedFrom,proto3,oneof" json:"mergedFrom,omitempty"`
	ActiveTarget  *ActiveTarget          `protobuf:"bytes,5,opt,name=activeTarget,proto3,oneof" json:"activeTarget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipType) Reset() {
	*x = RelationshipType{}
	mi := &file_components_relationships_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipType) ProtoMessage() {}

func (x *RelationshipType) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipType.ProtoReflect.Descriptor instead.
func (*RelationshipType) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{2}
}

func (x *RelationshipType) GetTrackedBy() *TrackedBy {
	if x != nil {
		return x.TrackedBy
	}
	return nil
}

func (x *RelationshipType) GetGroupChild() *GroupChild {
	if x != nil {
		return x.GroupChild
	}
	return nil
}

func (x *RelationshipType) GetGroupParent() *GroupParent {
	if x != nil {
		return x.GroupParent
	}
	return nil
}

func (x *RelationshipType) GetMergedFrom() *MergedFrom {
	if x != nil {
		return x.MergedFrom
	}
	return nil
}

func (x *RelationshipType) GetActiveTarget() *ActiveTarget {
	if x != nil {
		return x.ActiveTarget
	}
	return nil
}

type TrackedBy struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ActivelyTrackingSensors  *Sensors               `protobuf:"bytes,1,opt,name=activelyTrackingSensors,proto3,oneof" json:"activelyTrackingSensors,omitempty"`
	LastMeasurementTimeStamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lastMeasurementTimeStamp,proto3,oneof" json:"lastMeasurementTimeStamp,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrackedBy) Reset() {
	*x = TrackedBy{}
	mi := &file_components_relationships_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackedBy) ProtoMessage() {}

func (x *TrackedBy) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackedBy.ProtoReflect.Descriptor instead.
func (*TrackedBy) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{3}
}

func (x *TrackedBy) GetActivelyTrackingSensors() *Sensors {
	if x != nil {
		return x.ActivelyTrackingSensors
	}
	return nil
}

func (x *TrackedBy) GetLastMeasurementTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMeasurementTimeStamp
	}
	return nil
}

type GroupChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChild) Reset() {
	*x = GroupChild{}
	mi := &file_components_relationships_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChild) ProtoMessage() {}

func (x *GroupChild) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChild.ProtoReflect.Descriptor instead.
func (*GroupChild) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{4}
}

type GroupParent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupParent) Reset() {
	*x = GroupParent{}
	mi := &file_components_relationships_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupParent) ProtoMessage() {}

func (x *GroupParent) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupParent.ProtoReflect.Descriptor instead.
func (*GroupParent) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{5}
}

type MergedFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergedFrom) Reset() {
	*x = MergedFrom{}
	mi := &file_components_relationships_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergedFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergedFrom) ProtoMessage() {}

func (x *MergedFrom) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergedFrom.ProtoReflect.Descriptor instead.
func (*MergedFrom) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{6}
}

type ActiveTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveTarget) Reset() {
	*x = ActiveTarget{}
	mi := &file_components_relationships_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveTarget) ProtoMessage() {}

func (x *ActiveTarget) ProtoReflect() protoreflect.Message {
	mi := &file_components_relationships_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveTarget.ProtoReflect.Descriptor instead.
func (*ActiveTarget) Descriptor() ([]byte, []int) {
	return file_components_relationships_proto_rawDescGZIP(), []int{7}
}

var File_components_relationships_proto protoreflect.FileDescriptor

const file_components_relationships_proto_rawDesc = "" +
	"\n" +
	"\x1ecomponents/relationships.proto\x12\n" +
	"components\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18components/sensors.proto\"O\n" +
	"\rRelationships\x12>\n" +
	"\rrelationships\x18\x01 \x03(\v2\x18.components.RelationshipR\rrelationships\"\xf5\x01\n" +
	"\fRelationship\x12-\n" +
	"\x0frelatedEntityId\x18\x01 \x01(\tH\x00R\x0frelatedEntityId\x88\x01\x01\x12+\n" +
	"\x0erelationshipId\x18\x02 \x01(\tH\x01R\x0erelationshipId\x88\x01\x01\x12M\n" +
	"\x10relationshipType\x18\x03 \x01(\v2\x1c.components.RelationshipTypeH\x02R\x10relationshipType\x88\x01\x01B\x12\n" +
	"\x10_relatedEntityIdB\x11\n" +
	"\x0f_relationshipIdB\x13\n" +
	"\x11_relationshipType\"\x96\x03\n" +
	"\x10RelationshipType\x128\n" +
	"\ttrackedBy\x18\x01 \x01(\v2\x15.components.TrackedByH\x00R\ttrackedBy\x88\x01\x01\x12;\n" +
	"\n" +
	"groupChild\x18\x02 \x01(\v2\x16.components.GroupChildH\x01R\n" +
	"groupChild\x88\x01\x01\x12>\n" +
	"\vgroupParent\x18\x03 \x01(\v2\x17.components.GroupParentH\x02R\vgroupParent\x88\x01\x01\x12;\n" +
	"\n" +
	"mergedFrom\x18\x04 \x01(\v2\x16.components.MergedFromH\x03R\n" +
	"mergedFrom\x88\x01\x01\x12A\n" +
	"\factiveTarget\x18\x05 \x01(\v2\x18.components.ActiveTargetH\x04R\factiveTarget\x88\x01\x01B\f\n" +
	"\n" +
	"_trackedByB\r\n" +
	"\v_groupChildB\x0e\n" +
	"\f_groupParentB\r\n" +
	"\v_mergedFromB\x0f\n" +
	"\r_activeTarget\"\xf5\x01\n" +
	"\tTrackedBy\x12R\n" +
	"\x17activelyTrackingSensors\x18\x01 \x01(\v2\x13.components.SensorsH\x00R\x17activelyTrackingSensors\x88\x01\x01\x12[\n" +
	"\x18lastMeasurementTimeStamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x18lastMeasurementTimeStamp\x88\x01\x01B\x1a\n" +
	"\x18_activelyTrackingSensorsB\x1b\n" +
	"\x19_lastMeasurementTimeStamp\"\f\n" +
	"\n" +
	"GroupChild\"\r\n" +
	"\vGroupParent\"\f\n" +
	"\n" +
	"MergedFrom\"\x0e\n" +
	"\fActiveTargetB\rZ\v/componentsb\x06proto3"

var (
	file_components_relationships_proto_rawDescOnce sync.Once
	file_components_relationships_proto_rawDescData []byte
)

func file_components_relationships_proto_rawDescGZIP() []byte {
	file_components_relationships_proto_rawDescOnce.Do(func() {
		file_components_relationships_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_relationships_proto_rawDesc), len(file_components_relationships_proto_rawDesc)))
	})
	return file_components_relationships_proto_rawDescData
}

var file_components_relationships_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_components_relationships_proto_goTypes = []any{
	(*Relationships)(nil),         // 0: components.Relationships
	(*Relationship)(nil),          // 1: components.Relationship
	(*RelationshipType)(nil),      // 2: components.RelationshipType
	(*TrackedBy)(nil),             // 3: components.TrackedBy
	(*GroupChild)(nil),            // 4: components.GroupChild
	(*GroupParent)(nil),           // 5: components.GroupParent
	(*MergedFrom)(nil),            // 6: components.MergedFrom
	(*ActiveTarget)(nil),          // 7: components.ActiveTarget
	(*Sensors)(nil),               // 8: components.Sensors
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_components_relationships_proto_depIdxs = []int32{
	1, // 0: components.Relationships.relationships:type_name -> components.Relationship
	2, // 1: components.Relationship.relationshipType:type_name -> components.RelationshipType
	3, // 2: components.RelationshipType.trackedBy:type_name -> components.TrackedBy
	4, // 3: components.RelationshipType.groupChild:type_name -> components.GroupChild
	5, // 4: components.RelationshipType.groupParent:type_name -> components.GroupParent
	6, // 5: components.RelationshipType.mergedFrom:type_name -> components.MergedFrom
	7, // 6: components.RelationshipType.activeTarget:type_name -> components.ActiveTarget
	8, // 7: components.TrackedBy.activelyTrackingSensors:type_name -> components.Sensors
	9, // 8: components.TrackedBy.lastMeasurementTimeStamp:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_components_relationships_proto_init() }
func file_components_relationships_proto_init() {
	if File_components_relationships_proto != nil {
		return
	}
	file_components_sensors_proto_init()
	file_components_relationships_proto_msgTypes[1].OneofWrappers = []any{}
	file_components_relationships_proto_msgTypes[2].OneofWrappers = []any{}
	file_components_relationships_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_relationships_proto_rawDesc), len(file_components_relationships_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_relationships_proto_goTypes,
		DependencyIndexes: file_components_relationships_proto_depIdxs,
		MessageInfos:      file_components_relationships_proto_msgTypes,
	}.Build()
	File_components_relationships_proto = out.File
	file_components_relationships_proto_goTypes = nil
	file_components_relationships_proto_depIdxs = nil
}
