// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/route_details.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteDetails struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DestinationName      string                 `protobuf:"bytes,1,opt,name=destinationName,proto3" json:"destinationName,omitempty"`
	EstimatedArrivalTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=estimatedArrivalTime,proto3" json:"estimatedArrivalTime,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RouteDetails) Reset() {
	*x = RouteDetails{}
	mi := &file_components_route_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDetails) ProtoMessage() {}

func (x *RouteDetails) ProtoReflect() protoreflect.Message {
	mi := &file_components_route_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDetails.ProtoReflect.Descriptor instead.
func (*RouteDetails) Descriptor() ([]byte, []int) {
	return file_components_route_details_proto_rawDescGZIP(), []int{0}
}

func (x *RouteDetails) GetDestinationName() string {
	if x != nil {
		return x.DestinationName
	}
	return ""
}

func (x *RouteDetails) GetEstimatedArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedArrivalTime
	}
	return nil
}

var File_components_route_details_proto protoreflect.FileDescriptor

const file_components_route_details_proto_rawDesc = "" +
	"\n" +
	"\x1ecomponents/route_details.proto\x12\n" +
	"components\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\fRouteDetails\x12(\n" +
	"\x0fdestinationName\x18\x01 \x01(\tR\x0fdestinationName\x12N\n" +
	"\x14estimatedArrivalTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x14estimatedArrivalTimeB\rZ\v/componentsb\x06proto3"

var (
	file_components_route_details_proto_rawDescOnce sync.Once
	file_components_route_details_proto_rawDescData []byte
)

func file_components_route_details_proto_rawDescGZIP() []byte {
	file_components_route_details_proto_rawDescOnce.Do(func() {
		file_components_route_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_route_details_proto_rawDesc), len(file_components_route_details_proto_rawDesc)))
	})
	return file_components_route_details_proto_rawDescData
}

var file_components_route_details_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_route_details_proto_goTypes = []any{
	(*RouteDetails)(nil),          // 0: components.RouteDetails
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_components_route_details_proto_depIdxs = []int32{
	1, // 0: components.RouteDetails.estimatedArrivalTime:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_route_details_proto_init() }
func file_components_route_details_proto_init() {
	if File_components_route_details_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_route_details_proto_rawDesc), len(file_components_route_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_route_details_proto_goTypes,
		DependencyIndexes: file_components_route_details_proto_depIdxs,
		MessageInfos:      file_components_route_details_proto_msgTypes,
	}.Build()
	File_components_route_details_proto = out.File
	file_components_route_details_proto_goTypes = nil
	file_components_route_details_proto_depIdxs = nil
}
