// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/target_priority.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetPriority struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HighValueTarget *HighValueTarget       `protobuf:"bytes,1,opt,name=highValueTarget,proto3" json:"highValueTarget,omitempty"`
	Threat          *Threat                `protobuf:"bytes,2,opt,name=threat,proto3" json:"threat,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TargetPriority) Reset() {
	*x = TargetPriority{}
	mi := &file_components_target_priority_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPriority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPriority) ProtoMessage() {}

func (x *TargetPriority) ProtoReflect() protoreflect.Message {
	mi := &file_components_target_priority_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPriority.ProtoReflect.Descriptor instead.
func (*TargetPriority) Descriptor() ([]byte, []int) {
	return file_components_target_priority_proto_rawDescGZIP(), []int{0}
}

func (x *TargetPriority) GetHighValueTarget() *HighValueTarget {
	if x != nil {
		return x.HighValueTarget
	}
	return nil
}

func (x *TargetPriority) GetThreat() *Threat {
	if x != nil {
		return x.Threat
	}
	return nil
}

type HighValueTarget struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsHighValueTarget bool                   `protobuf:"varint,1,opt,name=isHighValueTarget,proto3" json:"isHighValueTarget,omitempty"`
	TargetPriority    uint32                 `protobuf:"varint,2,opt,name=targetPriority,proto3" json:"targetPriority,omitempty"`
	TargetMatches     []*TargetMatch         `protobuf:"bytes,3,rep,name=targetMatches,proto3" json:"targetMatches,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HighValueTarget) Reset() {
	*x = HighValueTarget{}
	mi := &file_components_target_priority_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighValueTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighValueTarget) ProtoMessage() {}

func (x *HighValueTarget) ProtoReflect() protoreflect.Message {
	mi := &file_components_target_priority_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighValueTarget.ProtoReflect.Descriptor instead.
func (*HighValueTarget) Descriptor() ([]byte, []int) {
	return file_components_target_priority_proto_rawDescGZIP(), []int{1}
}

func (x *HighValueTarget) GetIsHighValueTarget() bool {
	if x != nil {
		return x.IsHighValueTarget
	}
	return false
}

func (x *HighValueTarget) GetTargetPriority() uint32 {
	if x != nil {
		return x.TargetPriority
	}
	return 0
}

func (x *HighValueTarget) GetTargetMatches() []*TargetMatch {
	if x != nil {
		return x.TargetMatches
	}
	return nil
}

type TargetMatch struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	HighValueTargetListId        string                 `protobuf:"bytes,1,opt,name=highValueTargetListId,proto3" json:"highValueTargetListId,omitempty"`
	HighValueTargetDescriptionId string                 `protobuf:"bytes,2,opt,name=highValueTargetDescriptionId,proto3" json:"highValueTargetDescriptionId,omitempty"`
	IsHighPayoffTarget           bool                   `protobuf:"varint,3,opt,name=isHighPayoffTarget,proto3" json:"isHighPayoffTarget,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TargetMatch) Reset() {
	*x = TargetMatch{}
	mi := &file_components_target_priority_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetMatch) ProtoMessage() {}

func (x *TargetMatch) ProtoReflect() protoreflect.Message {
	mi := &file_components_target_priority_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetMatch.ProtoReflect.Descriptor instead.
func (*TargetMatch) Descriptor() ([]byte, []int) {
	return file_components_target_priority_proto_rawDescGZIP(), []int{2}
}

func (x *TargetMatch) GetHighValueTargetListId() string {
	if x != nil {
		return x.HighValueTargetListId
	}
	return ""
}

func (x *TargetMatch) GetHighValueTargetDescriptionId() string {
	if x != nil {
		return x.HighValueTargetDescriptionId
	}
	return ""
}

func (x *TargetMatch) GetIsHighPayoffTarget() bool {
	if x != nil {
		return x.IsHighPayoffTarget
	}
	return false
}

type Threat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsThreat      bool                   `protobuf:"varint,1,opt,name=isThreat,proto3" json:"isThreat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_components_target_priority_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_components_target_priority_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_components_target_priority_proto_rawDescGZIP(), []int{3}
}

func (x *Threat) GetIsThreat() bool {
	if x != nil {
		return x.IsThreat
	}
	return false
}

var File_components_target_priority_proto protoreflect.FileDescriptor

const file_components_target_priority_proto_rawDesc = "" +
	"\n" +
	" components/target_priority.proto\x12\n" +
	"components\"\x83\x01\n" +
	"\x0eTargetPriority\x12E\n" +
	"\x0fhighValueTarget\x18\x01 \x01(\v2\x1b.components.HighValueTargetR\x0fhighValueTarget\x12*\n" +
	"\x06threat\x18\x02 \x01(\v2\x12.components.ThreatR\x06threat\"\xa6\x01\n" +
	"\x0fHighValueTarget\x12,\n" +
	"\x11isHighValueTarget\x18\x01 \x01(\bR\x11isHighValueTarget\x12&\n" +
	"\x0etargetPriority\x18\x02 \x01(\rR\x0etargetPriority\x12=\n" +
	"\rtargetMatches\x18\x03 \x03(\v2\x17.components.TargetMatchR\rtargetMatches\"\xb7\x01\n" +
	"\vTargetMatch\x124\n" +
	"\x15highValueTargetListId\x18\x01 \x01(\tR\x15highValueTargetListId\x12B\n" +
	"\x1chighValueTargetDescriptionId\x18\x02 \x01(\tR\x1chighValueTargetDescriptionId\x12.\n" +
	"\x12isHighPayoffTarget\x18\x03 \x01(\bR\x12isHighPayoffTarget\"$\n" +
	"\x06Threat\x12\x1a\n" +
	"\bisThreat\x18\x01 \x01(\bR\bisThreatB\rZ\v/componentsb\x06proto3"

var (
	file_components_target_priority_proto_rawDescOnce sync.Once
	file_components_target_priority_proto_rawDescData []byte
)

func file_components_target_priority_proto_rawDescGZIP() []byte {
	file_components_target_priority_proto_rawDescOnce.Do(func() {
		file_components_target_priority_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_target_priority_proto_rawDesc), len(file_components_target_priority_proto_rawDesc)))
	})
	return file_components_target_priority_proto_rawDescData
}

var file_components_target_priority_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_target_priority_proto_goTypes = []any{
	(*TargetPriority)(nil),  // 0: components.TargetPriority
	(*HighValueTarget)(nil), // 1: components.HighValueTarget
	(*TargetMatch)(nil),     // 2: components.TargetMatch
	(*Threat)(nil),          // 3: components.Threat
}
var file_components_target_priority_proto_depIdxs = []int32{
	1, // 0: components.TargetPriority.highValueTarget:type_name -> components.HighValueTarget
	3, // 1: components.TargetPriority.threat:type_name -> components.Threat
	2, // 2: components.HighValueTarget.targetMatches:type_name -> components.TargetMatch
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_target_priority_proto_init() }
func file_components_target_priority_proto_init() {
	if File_components_target_priority_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_target_priority_proto_rawDesc), len(file_components_target_priority_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_target_priority_proto_goTypes,
		DependencyIndexes: file_components_target_priority_proto_depIdxs,
		MessageInfos:      file_components_target_priority_proto_msgTypes,
	}.Build()
	File_components_target_priority_proto = out.File
	file_components_target_priority_proto_goTypes = nil
	file_components_target_priority_proto_depIdxs = nil
}
