// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/tracked.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AltitudeReference int32

const (
	AltitudeReference_ALTITUDE_REFERENCE_INVALID            AltitudeReference = 0
	AltitudeReference_ALTITUDE_REFERENCE_HEIGHT_ABOVE_WGS84 AltitudeReference = 1
	AltitudeReference_ALTITUDE_REFERENCE_HEIGHT_ABOVE_EGM96 AltitudeReference = 2
	AltitudeReference_ALTITUDE_REFERENCE_UNKNOWN            AltitudeReference = 3
	AltitudeReference_ALTITUDE_REFERENCE_BAROMETRIC         AltitudeReference = 4
	AltitudeReference_ALTITUDE_REFERENCE_ABOVE_SEA_FLOOR    AltitudeReference = 5
	AltitudeReference_ALTITUDE_REFERENCE_BELOW_SEA_SURFACE  AltitudeReference = 6
)

// Enum value maps for AltitudeReference.
var (
	AltitudeReference_name = map[int32]string{
		0: "ALTITUDE_REFERENCE_INVALID",
		1: "ALTITUDE_REFERENCE_HEIGHT_ABOVE_WGS84",
		2: "ALTITUDE_REFERENCE_HEIGHT_ABOVE_EGM96",
		3: "ALTITUDE_REFERENCE_UNKNOWN",
		4: "ALTITUDE_REFERENCE_BAROMETRIC",
		5: "ALTITUDE_REFERENCE_ABOVE_SEA_FLOOR",
		6: "ALTITUDE_REFERENCE_BELOW_SEA_SURFACE",
	}
	AltitudeReference_value = map[string]int32{
		"ALTITUDE_REFERENCE_INVALID":            0,
		"ALTITUDE_REFERENCE_HEIGHT_ABOVE_WGS84": 1,
		"ALTITUDE_REFERENCE_HEIGHT_ABOVE_EGM96": 2,
		"ALTITUDE_REFERENCE_UNKNOWN":            3,
		"ALTITUDE_REFERENCE_BAROMETRIC":         4,
		"ALTITUDE_REFERENCE_ABOVE_SEA_FLOOR":    5,
		"ALTITUDE_REFERENCE_BELOW_SEA_SURFACE":  6,
	}
)

func (x AltitudeReference) Enum() *AltitudeReference {
	p := new(AltitudeReference)
	*p = x
	return p
}

func (x AltitudeReference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AltitudeReference) Descriptor() protoreflect.EnumDescriptor {
	return file_components_tracked_proto_enumTypes[0].Descriptor()
}

func (AltitudeReference) Type() protoreflect.EnumType {
	return &file_components_tracked_proto_enumTypes[0]
}

func (x AltitudeReference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AltitudeReference.Descriptor instead.
func (AltitudeReference) EnumDescriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{0}
}

type Tracked struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TrackQualityWrapper int32                  `protobuf:"varint,1,opt,name=track_quality_wrapper,json=trackQualityWrapper,proto3" json:"track_quality_wrapper,omitempty"`
	SensorHits          int32                  `protobuf:"varint,2,opt,name=sensor_hits,json=sensorHits,proto3" json:"sensor_hits,omitempty"`
	NumberOfObjects     *NumberOfObjects       `protobuf:"bytes,3,opt,name=number_of_objects,json=numberOfObjects,proto3" json:"number_of_objects,omitempty"`
	RadarCrossSection   float64                `protobuf:"fixed64,4,opt,name=radar_cross_section,json=radarCrossSection,proto3" json:"radar_cross_section,omitempty"`
	LastMeasurementTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_measurement_time,json=lastMeasurementTime,proto3" json:"last_measurement_time,omitempty"`
	LineOfBearing       *LineOfBearing         `protobuf:"bytes,6,opt,name=line_of_bearing,json=lineOfBearing,proto3" json:"line_of_bearing,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tracked) Reset() {
	*x = Tracked{}
	mi := &file_components_tracked_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracked) ProtoMessage() {}

func (x *Tracked) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracked.ProtoReflect.Descriptor instead.
func (*Tracked) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{0}
}

func (x *Tracked) GetTrackQualityWrapper() int32 {
	if x != nil {
		return x.TrackQualityWrapper
	}
	return 0
}

func (x *Tracked) GetSensorHits() int32 {
	if x != nil {
		return x.SensorHits
	}
	return 0
}

func (x *Tracked) GetNumberOfObjects() *NumberOfObjects {
	if x != nil {
		return x.NumberOfObjects
	}
	return nil
}

func (x *Tracked) GetRadarCrossSection() float64 {
	if x != nil {
		return x.RadarCrossSection
	}
	return 0
}

func (x *Tracked) GetLastMeasurementTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMeasurementTime
	}
	return nil
}

func (x *Tracked) GetLineOfBearing() *LineOfBearing {
	if x != nil {
		return x.LineOfBearing
	}
	return nil
}

type NumberOfObjects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowerBound    uint32                 `protobuf:"varint,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound    uint32                 `protobuf:"varint,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberOfObjects) Reset() {
	*x = NumberOfObjects{}
	mi := &file_components_tracked_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberOfObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberOfObjects) ProtoMessage() {}

func (x *NumberOfObjects) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberOfObjects.ProtoReflect.Descriptor instead.
func (*NumberOfObjects) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{1}
}

func (x *NumberOfObjects) GetLowerBound() uint32 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *NumberOfObjects) GetUpperBound() uint32 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

type LineOfBearing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AngleOfArrival *AngleOfArrival        `protobuf:"bytes,1,opt,name=angle_of_arrival,json=angleOfArrival,proto3" json:"angle_of_arrival,omitempty"`
	RangeEstimateM *RangeEstimateM        `protobuf:"bytes,2,opt,name=range_estimate_m,json=rangeEstimateM,proto3" json:"range_estimate_m,omitempty"`
	MaxRangeM      *MaxRangeM             `protobuf:"bytes,3,opt,name=max_range_m,json=maxRangeM,proto3" json:"max_range_m,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LineOfBearing) Reset() {
	*x = LineOfBearing{}
	mi := &file_components_tracked_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineOfBearing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineOfBearing) ProtoMessage() {}

func (x *LineOfBearing) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineOfBearing.ProtoReflect.Descriptor instead.
func (*LineOfBearing) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{2}
}

func (x *LineOfBearing) GetAngleOfArrival() *AngleOfArrival {
	if x != nil {
		return x.AngleOfArrival
	}
	return nil
}

func (x *LineOfBearing) GetRangeEstimateM() *RangeEstimateM {
	if x != nil {
		return x.RangeEstimateM
	}
	return nil
}

func (x *LineOfBearing) GetMaxRangeM() *MaxRangeM {
	if x != nil {
		return x.MaxRangeM
	}
	return nil
}

type AngleOfArrival struct {
	state                          protoimpl.MessageState          `protogen:"open.v1"`
	RelativePose                   *RelativePose                   `protobuf:"bytes,1,opt,name=relative_pose,json=relativePose,proto3" json:"relative_pose,omitempty"`
	BearingElevationCovarianceRad2 *BearingElevationCovarianceRad2 `protobuf:"bytes,2,opt,name=bearing_elevation_covariance_rad2,json=bearingElevationCovarianceRad2,proto3" json:"bearing_elevation_covariance_rad2,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AngleOfArrival) Reset() {
	*x = AngleOfArrival{}
	mi := &file_components_tracked_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AngleOfArrival) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AngleOfArrival) ProtoMessage() {}

func (x *AngleOfArrival) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AngleOfArrival.ProtoReflect.Descriptor instead.
func (*AngleOfArrival) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{3}
}

func (x *AngleOfArrival) GetRelativePose() *RelativePose {
	if x != nil {
		return x.RelativePose
	}
	return nil
}

func (x *AngleOfArrival) GetBearingElevationCovarianceRad2() *BearingElevationCovarianceRad2 {
	if x != nil {
		return x.BearingElevationCovarianceRad2
	}
	return nil
}

type RelativePose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Pos                   `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	AttEnu        *AttitudeEnu           `protobuf:"bytes,2,opt,name=att_enu,json=attEnu,proto3" json:"att_enu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelativePose) Reset() {
	*x = RelativePose{}
	mi := &file_components_tracked_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativePose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativePose) ProtoMessage() {}

func (x *RelativePose) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativePose.ProtoReflect.Descriptor instead.
func (*RelativePose) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{4}
}

func (x *RelativePose) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *RelativePose) GetAttEnu() *AttitudeEnu {
	if x != nil {
		return x.AttEnu
	}
	return nil
}

type Pos struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Lon               float64                `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat               float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Alt               float64                `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Is2D              bool                   `protobuf:"varint,4,opt,name=is2d,proto3" json:"is2d,omitempty"`
	AltitudeReference AltitudeReference      `protobuf:"varint,5,opt,name=altitude_reference,json=altitudeReference,proto3,enum=components.AltitudeReference" json:"altitude_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Pos) Reset() {
	*x = Pos{}
	mi := &file_components_tracked_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{5}
}

func (x *Pos) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Pos) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Pos) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Pos) GetIs2D() bool {
	if x != nil {
		return x.Is2D
	}
	return false
}

func (x *Pos) GetAltitudeReference() AltitudeReference {
	if x != nil {
		return x.AltitudeReference
	}
	return AltitudeReference_ALTITUDE_REFERENCE_INVALID
}

type BearingElevationCovarianceRad2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mxx           float64                `protobuf:"fixed64,1,opt,name=mxx,proto3" json:"mxx,omitempty"`
	Mxy           float64                `protobuf:"fixed64,2,opt,name=mxy,proto3" json:"mxy,omitempty"`
	Myy           float64                `protobuf:"fixed64,3,opt,name=myy,proto3" json:"myy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BearingElevationCovarianceRad2) Reset() {
	*x = BearingElevationCovarianceRad2{}
	mi := &file_components_tracked_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearingElevationCovarianceRad2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearingElevationCovarianceRad2) ProtoMessage() {}

func (x *BearingElevationCovarianceRad2) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearingElevationCovarianceRad2.ProtoReflect.Descriptor instead.
func (*BearingElevationCovarianceRad2) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{6}
}

func (x *BearingElevationCovarianceRad2) GetMxx() float64 {
	if x != nil {
		return x.Mxx
	}
	return 0
}

func (x *BearingElevationCovarianceRad2) GetMxy() float64 {
	if x != nil {
		return x.Mxy
	}
	return 0
}

func (x *BearingElevationCovarianceRad2) GetMyy() float64 {
	if x != nil {
		return x.Myy
	}
	return 0
}

type RangeEstimateM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Sigma         float64                `protobuf:"fixed64,2,opt,name=sigma,proto3" json:"sigma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeEstimateM) Reset() {
	*x = RangeEstimateM{}
	mi := &file_components_tracked_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeEstimateM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeEstimateM) ProtoMessage() {}

func (x *RangeEstimateM) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeEstimateM.ProtoReflect.Descriptor instead.
func (*RangeEstimateM) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{7}
}

func (x *RangeEstimateM) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RangeEstimateM) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

type MaxRangeM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Sigma         float64                `protobuf:"fixed64,2,opt,name=sigma,proto3" json:"sigma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxRangeM) Reset() {
	*x = MaxRangeM{}
	mi := &file_components_tracked_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxRangeM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxRangeM) ProtoMessage() {}

func (x *MaxRangeM) ProtoReflect() protoreflect.Message {
	mi := &file_components_tracked_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxRangeM.ProtoReflect.Descriptor instead.
func (*MaxRangeM) Descriptor() ([]byte, []int) {
	return file_components_tracked_proto_rawDescGZIP(), []int{8}
}

func (x *MaxRangeM) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MaxRangeM) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

var File_components_tracked_proto protoreflect.FileDescriptor

const file_components_tracked_proto_rawDesc = "" +
	"\n" +
	"\x18components/tracked.proto\x12\n" +
	"components\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19components/location.proto\"\xea\x02\n" +
	"\aTracked\x122\n" +
	"\x15track_quality_wrapper\x18\x01 \x01(\x05R\x13trackQualityWrapper\x12\x1f\n" +
	"\vsensor_hits\x18\x02 \x01(\x05R\n" +
	"sensorHits\x12G\n" +
	"\x11number_of_objects\x18\x03 \x01(\v2\x1b.components.NumberOfObjectsR\x0fnumberOfObjects\x12.\n" +
	"\x13radar_cross_section\x18\x04 \x01(\x01R\x11radarCrossSection\x12N\n" +
	"\x15last_measurement_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x13lastMeasurementTime\x12A\n" +
	"\x0fline_of_bearing\x18\x06 \x01(\v2\x19.components.LineOfBearingR\rlineOfBearing\"S\n" +
	"\x0fNumberOfObjects\x12\x1f\n" +
	"\vlower_bound\x18\x01 \x01(\rR\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\rR\n" +
	"upperBound\"\xd2\x01\n" +
	"\rLineOfBearing\x12D\n" +
	"\x10angle_of_arrival\x18\x01 \x01(\v2\x1a.components.AngleOfArrivalR\x0eangleOfArrival\x12D\n" +
	"\x10range_estimate_m\x18\x02 \x01(\v2\x1a.components.RangeEstimateMR\x0erangeEstimateM\x125\n" +
	"\vmax_range_m\x18\x03 \x01(\v2\x15.components.MaxRangeMR\tmaxRangeM\"\xc6\x01\n" +
	"\x0eAngleOfArrival\x12=\n" +
	"\rrelative_pose\x18\x01 \x01(\v2\x18.components.RelativePoseR\frelativePose\x12u\n" +
	"!bearing_elevation_covariance_rad2\x18\x02 \x01(\v2*.components.BearingElevationCovarianceRad2R\x1ebearingElevationCovarianceRad2\"c\n" +
	"\fRelativePose\x12!\n" +
	"\x03pos\x18\x01 \x01(\v2\x0f.components.PosR\x03pos\x120\n" +
	"\aatt_enu\x18\x02 \x01(\v2\x17.components.AttitudeEnuR\x06attEnu\"\x9d\x01\n" +
	"\x03Pos\x12\x10\n" +
	"\x03lon\x18\x01 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x01R\x03alt\x12\x12\n" +
	"\x04is2d\x18\x04 \x01(\bR\x04is2d\x12L\n" +
	"\x12altitude_reference\x18\x05 \x01(\x0e2\x1d.components.AltitudeReferenceR\x11altitudeReference\"V\n" +
	"\x1eBearingElevationCovarianceRad2\x12\x10\n" +
	"\x03mxx\x18\x01 \x01(\x01R\x03mxx\x12\x10\n" +
	"\x03mxy\x18\x02 \x01(\x01R\x03mxy\x12\x10\n" +
	"\x03myy\x18\x03 \x01(\x01R\x03myy\"<\n" +
	"\x0eRangeEstimateM\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x14\n" +
	"\x05sigma\x18\x02 \x01(\x01R\x05sigma\"7\n" +
	"\tMaxRangeM\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x14\n" +
	"\x05sigma\x18\x02 \x01(\x01R\x05sigma*\x9e\x02\n" +
	"\x11AltitudeReference\x12\x1e\n" +
	"\x1aALTITUDE_REFERENCE_INVALID\x10\x00\x12)\n" +
	"%ALTITUDE_REFERENCE_HEIGHT_ABOVE_WGS84\x10\x01\x12)\n" +
	"%ALTITUDE_REFERENCE_HEIGHT_ABOVE_EGM96\x10\x02\x12\x1e\n" +
	"\x1aALTITUDE_REFERENCE_UNKNOWN\x10\x03\x12!\n" +
	"\x1dALTITUDE_REFERENCE_BAROMETRIC\x10\x04\x12&\n" +
	"\"ALTITUDE_REFERENCE_ABOVE_SEA_FLOOR\x10\x05\x12(\n" +
	"$ALTITUDE_REFERENCE_BELOW_SEA_SURFACE\x10\x06B\rZ\v/componentsb\x06proto3"

var (
	file_components_tracked_proto_rawDescOnce sync.Once
	file_components_tracked_proto_rawDescData []byte
)

func file_components_tracked_proto_rawDescGZIP() []byte {
	file_components_tracked_proto_rawDescOnce.Do(func() {
		file_components_tracked_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_tracked_proto_rawDesc), len(file_components_tracked_proto_rawDesc)))
	})
	return file_components_tracked_proto_rawDescData
}

var file_components_tracked_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_tracked_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_components_tracked_proto_goTypes = []any{
	(AltitudeReference)(0),                 // 0: components.AltitudeReference
	(*Tracked)(nil),                        // 1: components.Tracked
	(*NumberOfObjects)(nil),                // 2: components.NumberOfObjects
	(*LineOfBearing)(nil),                  // 3: components.LineOfBearing
	(*AngleOfArrival)(nil),                 // 4: components.AngleOfArrival
	(*RelativePose)(nil),                   // 5: components.RelativePose
	(*Pos)(nil),                            // 6: components.Pos
	(*BearingElevationCovarianceRad2)(nil), // 7: components.BearingElevationCovarianceRad2
	(*RangeEstimateM)(nil),                 // 8: components.RangeEstimateM
	(*MaxRangeM)(nil),                      // 9: components.MaxRangeM
	(*timestamppb.Timestamp)(nil),          // 10: google.protobuf.Timestamp
	(*AttitudeEnu)(nil),                    // 11: components.AttitudeEnu
}
var file_components_tracked_proto_depIdxs = []int32{
	2,  // 0: components.Tracked.number_of_objects:type_name -> components.NumberOfObjects
	10, // 1: components.Tracked.last_measurement_time:type_name -> google.protobuf.Timestamp
	3,  // 2: components.Tracked.line_of_bearing:type_name -> components.LineOfBearing
	4,  // 3: components.LineOfBearing.angle_of_arrival:type_name -> components.AngleOfArrival
	8,  // 4: components.LineOfBearing.range_estimate_m:type_name -> components.RangeEstimateM
	9,  // 5: components.LineOfBearing.max_range_m:type_name -> components.MaxRangeM
	5,  // 6: components.AngleOfArrival.relative_pose:type_name -> components.RelativePose
	7,  // 7: components.AngleOfArrival.bearing_elevation_covariance_rad2:type_name -> components.BearingElevationCovarianceRad2
	6,  // 8: components.RelativePose.pos:type_name -> components.Pos
	11, // 9: components.RelativePose.att_enu:type_name -> components.AttitudeEnu
	0,  // 10: components.Pos.altitude_reference:type_name -> components.AltitudeReference
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_components_tracked_proto_init() }
func file_components_tracked_proto_init() {
	if File_components_tracked_proto != nil {
		return
	}
	file_components_location_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_tracked_proto_rawDesc), len(file_components_tracked_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_tracked_proto_goTypes,
		DependencyIndexes: file_components_tracked_proto_depIdxs,
		EnumInfos:         file_components_tracked_proto_enumTypes,
		MessageInfos:      file_components_tracked_proto_msgTypes,
	}.Build()
	File_components_tracked_proto = out.File
	file_components_tracked_proto_goTypes = nil
	file_components_tracked_proto_depIdxs = nil
}
