// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/overrides.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverideStatus int32

const (
	OverideStatus_OVERRIDE_STATUS_INVALID          OverideStatus = 0
	OverideStatus_OVERRIDE_STATUS_APPLIED          OverideStatus = 1
	OverideStatus_OVERRIDE_STATUS_PENDING          OverideStatus = 2
	OverideStatus_OVERRIDE_STATUS_TIMEOUT          OverideStatus = 3
	OverideStatus_OVERRIDE_STATUS_REJECTED         OverideStatus = 4
	OverideStatus_OVERRIDE_STATUS_DELETION_PENDING OverideStatus = 5
)

// Enum value maps for OverideStatus.
var (
	OverideStatus_name = map[int32]string{
		0: "OVERRIDE_STATUS_INVALID",
		1: "OVERRIDE_STATUS_APPLIED",
		2: "OVERRIDE_STATUS_PENDING",
		3: "OVERRIDE_STATUS_TIMEOUT",
		4: "OVERRIDE_STATUS_REJECTED",
		5: "OVERRIDE_STATUS_DELETION_PENDING",
	}
	OverideStatus_value = map[string]int32{
		"OVERRIDE_STATUS_INVALID":          0,
		"OVERRIDE_STATUS_APPLIED":          1,
		"OVERRIDE_STATUS_PENDING":          2,
		"OVERRIDE_STATUS_TIMEOUT":          3,
		"OVERRIDE_STATUS_REJECTED":         4,
		"OVERRIDE_STATUS_DELETION_PENDING": 5,
	}
)

func (x OverideStatus) Enum() *OverideStatus {
	p := new(OverideStatus)
	*p = x
	return p
}

func (x OverideStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverideStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_components_overrides_proto_enumTypes[0].Descriptor()
}

func (OverideStatus) Type() protoreflect.EnumType {
	return &file_components_overrides_proto_enumTypes[0]
}

func (x OverideStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverideStatus.Descriptor instead.
func (OverideStatus) EnumDescriptor() ([]byte, []int) {
	return file_components_overrides_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_OVERRIDE_TYPE_INVALID     Type = 0
	Type_OVERRIDE_TYPE_LIVE        Type = 1
	Type_OVERRIDE_TYPE_POST_EXPIRY Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "OVERRIDE_TYPE_INVALID",
		1: "OVERRIDE_TYPE_LIVE",
		2: "OVERRIDE_TYPE_POST_EXPIRY",
	}
	Type_value = map[string]int32{
		"OVERRIDE_TYPE_INVALID":     0,
		"OVERRIDE_TYPE_LIVE":        1,
		"OVERRIDE_TYPE_POST_EXPIRY": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_components_overrides_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_components_overrides_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_components_overrides_proto_rawDescGZIP(), []int{1}
}

type Overrides struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Override      []*Override            `protobuf:"bytes,1,rep,name=override,proto3" json:"override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overrides) Reset() {
	*x = Overrides{}
	mi := &file_components_overrides_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overrides) ProtoMessage() {}

func (x *Overrides) ProtoReflect() protoreflect.Message {
	mi := &file_components_overrides_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overrides.ProtoReflect.Descriptor instead.
func (*Overrides) Descriptor() ([]byte, []int) {
	return file_components_overrides_proto_rawDescGZIP(), []int{0}
}

func (x *Overrides) GetOverride() []*Override {
	if x != nil {
		return x.Override
	}
	return nil
}

type Override struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	FieldPath        string                 `protobuf:"bytes,2,opt,name=fieldPath,proto3" json:"fieldPath,omitempty"`
	MaskedFieldValue *anypb.Any             `protobuf:"bytes,3,opt,name=maskedFieldValue,proto3" json:"maskedFieldValue,omitempty"`
	Status           OverideStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=components.OverideStatus" json:"status,omitempty"`
	Provenance       *Provenance            `protobuf:"bytes,5,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Type             Type                   `protobuf:"varint,6,opt,name=type,proto3,enum=components.Type" json:"type,omitempty"`
	RequestTimeStamp string                 `protobuf:"bytes,7,opt,name=requestTimeStamp,proto3" json:"requestTimeStamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Override) Reset() {
	*x = Override{}
	mi := &file_components_overrides_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Override) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Override) ProtoMessage() {}

func (x *Override) ProtoReflect() protoreflect.Message {
	mi := &file_components_overrides_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Override.ProtoReflect.Descriptor instead.
func (*Override) Descriptor() ([]byte, []int) {
	return file_components_overrides_proto_rawDescGZIP(), []int{1}
}

func (x *Override) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Override) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *Override) GetMaskedFieldValue() *anypb.Any {
	if x != nil {
		return x.MaskedFieldValue
	}
	return nil
}

func (x *Override) GetStatus() OverideStatus {
	if x != nil {
		return x.Status
	}
	return OverideStatus_OVERRIDE_STATUS_INVALID
}

func (x *Override) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Override) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_OVERRIDE_TYPE_INVALID
}

func (x *Override) GetRequestTimeStamp() string {
	if x != nil {
		return x.RequestTimeStamp
	}
	return ""
}

var File_components_overrides_proto protoreflect.FileDescriptor

const file_components_overrides_proto_rawDesc = "" +
	"\n" +
	"\x1acomponents/overrides.proto\x12\n" +
	"components\x1a\x19google/protobuf/any.proto\x1a\x1bcomponents/provenance.proto\"=\n" +
	"\tOverrides\x120\n" +
	"\boverride\x18\x01 \x03(\v2\x14.components.OverrideR\boverride\"\xc5\x02\n" +
	"\bOverride\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tfieldPath\x18\x02 \x01(\tR\tfieldPath\x12@\n" +
	"\x10maskedFieldValue\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x10maskedFieldValue\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.components.OverideStatusR\x06status\x126\n" +
	"\n" +
	"provenance\x18\x05 \x01(\v2\x16.components.ProvenanceR\n" +
	"provenance\x12$\n" +
	"\x04type\x18\x06 \x01(\x0e2\x10.components.TypeR\x04type\x12*\n" +
	"\x10requestTimeStamp\x18\a \x01(\tR\x10requestTimeStamp*\xc7\x01\n" +
	"\rOverideStatus\x12\x1b\n" +
	"\x17OVERRIDE_STATUS_INVALID\x10\x00\x12\x1b\n" +
	"\x17OVERRIDE_STATUS_APPLIED\x10\x01\x12\x1b\n" +
	"\x17OVERRIDE_STATUS_PENDING\x10\x02\x12\x1b\n" +
	"\x17OVERRIDE_STATUS_TIMEOUT\x10\x03\x12\x1c\n" +
	"\x18OVERRIDE_STATUS_REJECTED\x10\x04\x12$\n" +
	" OVERRIDE_STATUS_DELETION_PENDING\x10\x05*X\n" +
	"\x04Type\x12\x19\n" +
	"\x15OVERRIDE_TYPE_INVALID\x10\x00\x12\x16\n" +
	"\x12OVERRIDE_TYPE_LIVE\x10\x01\x12\x1d\n" +
	"\x19OVERRIDE_TYPE_POST_EXPIRY\x10\x02B\rZ\v/componentsb\x06proto3"

var (
	file_components_overrides_proto_rawDescOnce sync.Once
	file_components_overrides_proto_rawDescData []byte
)

func file_components_overrides_proto_rawDescGZIP() []byte {
	file_components_overrides_proto_rawDescOnce.Do(func() {
		file_components_overrides_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_overrides_proto_rawDesc), len(file_components_overrides_proto_rawDesc)))
	})
	return file_components_overrides_proto_rawDescData
}

var file_components_overrides_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_components_overrides_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_overrides_proto_goTypes = []any{
	(OverideStatus)(0), // 0: components.OverideStatus
	(Type)(0),          // 1: components.Type
	(*Overrides)(nil),  // 2: components.Overrides
	(*Override)(nil),   // 3: components.Override
	(*anypb.Any)(nil),  // 4: google.protobuf.Any
	(*Provenance)(nil), // 5: components.Provenance
}
var file_components_overrides_proto_depIdxs = []int32{
	3, // 0: components.Overrides.override:type_name -> components.Override
	4, // 1: components.Override.maskedFieldValue:type_name -> google.protobuf.Any
	0, // 2: components.Override.status:type_name -> components.OverideStatus
	5, // 3: components.Override.provenance:type_name -> components.Provenance
	1, // 4: components.Override.type:type_name -> components.Type
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_components_overrides_proto_init() }
func file_components_overrides_proto_init() {
	if File_components_overrides_proto != nil {
		return
	}
	file_components_provenance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_overrides_proto_rawDesc), len(file_components_overrides_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_overrides_proto_goTypes,
		DependencyIndexes: file_components_overrides_proto_depIdxs,
		EnumInfos:         file_components_overrides_proto_enumTypes,
		MessageInfos:      file_components_overrides_proto_msgTypes,
	}.Build()
	File_components_overrides_proto = out.File
	file_components_overrides_proto_goTypes = nil
	file_components_overrides_proto_depIdxs = nil
}
