// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: components/transponder_codes.proto

package components

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterrogationResponse int32

const (
	InterrogationResponse_INTERROGATION_RESPONSE_INVALID     InterrogationResponse = 0
	InterrogationResponse_INTERROGATION_RESPONSE_CORRECT     InterrogationResponse = 1
	InterrogationResponse_INTERROGATION_RESPONSE_INCORRECT   InterrogationResponse = 2
	InterrogationResponse_INTERROGATION_RESPONSE_NO_RESPONSE InterrogationResponse = 3
)

// Enum value maps for InterrogationResponse.
var (
	InterrogationResponse_name = map[int32]string{
		0: "INTERROGATION_RESPONSE_INVALID",
		1: "INTERROGATION_RESPONSE_CORRECT",
		2: "INTERROGATION_RESPONSE_INCORRECT",
		3: "INTERROGATION_RESPONSE_NO_RESPONSE",
	}
	InterrogationResponse_value = map[string]int32{
		"INTERROGATION_RESPONSE_INVALID":     0,
		"INTERROGATION_RESPONSE_CORRECT":     1,
		"INTERROGATION_RESPONSE_INCORRECT":   2,
		"INTERROGATION_RESPONSE_NO_RESPONSE": 3,
	}
)

func (x InterrogationResponse) Enum() *InterrogationResponse {
	p := new(InterrogationResponse)
	*p = x
	return p
}

func (x InterrogationResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterrogationResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_components_transponder_codes_proto_enumTypes[0].Descriptor()
}

func (InterrogationResponse) Type() protoreflect.EnumType {
	return &file_components_transponder_codes_proto_enumTypes[0]
}

func (x InterrogationResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterrogationResponse.Descriptor instead.
func (InterrogationResponse) EnumDescriptor() ([]byte, []int) {
	return file_components_transponder_codes_proto_rawDescGZIP(), []int{0}
}

type Mode5 struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Mode5InterrogationResponse InterrogationResponse  `protobuf:"varint,1,opt,name=mode5_interrogation_response,json=mode5InterrogationResponse,proto3,enum=components.InterrogationResponse" json:"mode5_interrogation_response,omitempty"`
	Mode5                      uint32                 `protobuf:"varint,2,opt,name=mode5,proto3" json:"mode5,omitempty"`
	Mode5PlatformId            uint32                 `protobuf:"varint,3,opt,name=mode5_platform_id,json=mode5PlatformId,proto3" json:"mode5_platform_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Mode5) Reset() {
	*x = Mode5{}
	mi := &file_components_transponder_codes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode5) ProtoMessage() {}

func (x *Mode5) ProtoReflect() protoreflect.Message {
	mi := &file_components_transponder_codes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode5.ProtoReflect.Descriptor instead.
func (*Mode5) Descriptor() ([]byte, []int) {
	return file_components_transponder_codes_proto_rawDescGZIP(), []int{0}
}

func (x *Mode5) GetMode5InterrogationResponse() InterrogationResponse {
	if x != nil {
		return x.Mode5InterrogationResponse
	}
	return InterrogationResponse_INTERROGATION_RESPONSE_INVALID
}

func (x *Mode5) GetMode5() uint32 {
	if x != nil {
		return x.Mode5
	}
	return 0
}

func (x *Mode5) GetMode5PlatformId() uint32 {
	if x != nil {
		return x.Mode5PlatformId
	}
	return 0
}

type ModeS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       uint32                 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeS) Reset() {
	*x = ModeS{}
	mi := &file_components_transponder_codes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeS) ProtoMessage() {}

func (x *ModeS) ProtoReflect() protoreflect.Message {
	mi := &file_components_transponder_codes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeS.ProtoReflect.Descriptor instead.
func (*ModeS) Descriptor() ([]byte, []int) {
	return file_components_transponder_codes_proto_rawDescGZIP(), []int{1}
}

func (x *ModeS) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModeS) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type TransponderCodes struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Mode1                      uint32                 `protobuf:"varint,1,opt,name=mode1,proto3" json:"mode1,omitempty"`
	Mode2                      uint32                 `protobuf:"varint,2,opt,name=mode2,proto3" json:"mode2,omitempty"`
	Mode3                      uint32                 `protobuf:"varint,3,opt,name=mode3,proto3" json:"mode3,omitempty"`
	Mode4InterrogationResponse InterrogationResponse  `protobuf:"varint,4,opt,name=mode4_interrogation_response,json=mode4InterrogationResponse,proto3,enum=components.InterrogationResponse" json:"mode4_interrogation_response,omitempty"`
	Mode5                      *Mode5                 `protobuf:"bytes,5,opt,name=mode5,proto3" json:"mode5,omitempty"`
	ModeS                      *ModeS                 `protobuf:"bytes,6,opt,name=modeS,proto3" json:"modeS,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TransponderCodes) Reset() {
	*x = TransponderCodes{}
	mi := &file_components_transponder_codes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransponderCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransponderCodes) ProtoMessage() {}

func (x *TransponderCodes) ProtoReflect() protoreflect.Message {
	mi := &file_components_transponder_codes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransponderCodes.ProtoReflect.Descriptor instead.
func (*TransponderCodes) Descriptor() ([]byte, []int) {
	return file_components_transponder_codes_proto_rawDescGZIP(), []int{2}
}

func (x *TransponderCodes) GetMode1() uint32 {
	if x != nil {
		return x.Mode1
	}
	return 0
}

func (x *TransponderCodes) GetMode2() uint32 {
	if x != nil {
		return x.Mode2
	}
	return 0
}

func (x *TransponderCodes) GetMode3() uint32 {
	if x != nil {
		return x.Mode3
	}
	return 0
}

func (x *TransponderCodes) GetMode4InterrogationResponse() InterrogationResponse {
	if x != nil {
		return x.Mode4InterrogationResponse
	}
	return InterrogationResponse_INTERROGATION_RESPONSE_INVALID
}

func (x *TransponderCodes) GetMode5() *Mode5 {
	if x != nil {
		return x.Mode5
	}
	return nil
}

func (x *TransponderCodes) GetModeS() *ModeS {
	if x != nil {
		return x.ModeS
	}
	return nil
}

var File_components_transponder_codes_proto protoreflect.FileDescriptor

const file_components_transponder_codes_proto_rawDesc = "" +
	"\n" +
	"\"components/transponder_codes.proto\x12\n" +
	"components\"\xae\x01\n" +
	"\x05Mode5\x12c\n" +
	"\x1cmode5_interrogation_response\x18\x01 \x01(\x0e2!.components.InterrogationResponseR\x1amode5InterrogationResponse\x12\x14\n" +
	"\x05mode5\x18\x02 \x01(\rR\x05mode5\x12*\n" +
	"\x11mode5_platform_id\x18\x03 \x01(\rR\x0fmode5PlatformId\"1\n" +
	"\x05ModeS\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\rR\aaddress\"\x8b\x02\n" +
	"\x10TransponderCodes\x12\x14\n" +
	"\x05mode1\x18\x01 \x01(\rR\x05mode1\x12\x14\n" +
	"\x05mode2\x18\x02 \x01(\rR\x05mode2\x12\x14\n" +
	"\x05mode3\x18\x03 \x01(\rR\x05mode3\x12c\n" +
	"\x1cmode4_interrogation_response\x18\x04 \x01(\x0e2!.components.InterrogationResponseR\x1amode4InterrogationResponse\x12'\n" +
	"\x05mode5\x18\x05 \x01(\v2\x11.components.Mode5R\x05mode5\x12'\n" +
	"\x05modeS\x18\x06 \x01(\v2\x11.components.ModeSR\x05modeS*\xad\x01\n" +
	"\x15InterrogationResponse\x12\"\n" +
	"\x1eINTERROGATION_RESPONSE_INVALID\x10\x00\x12\"\n" +
	"\x1eINTERROGATION_RESPONSE_CORRECT\x10\x01\x12$\n" +
	" INTERROGATION_RESPONSE_INCORRECT\x10\x02\x12&\n" +
	"\"INTERROGATION_RESPONSE_NO_RESPONSE\x10\x03B\rZ\v/componentsb\x06proto3"

var (
	file_components_transponder_codes_proto_rawDescOnce sync.Once
	file_components_transponder_codes_proto_rawDescData []byte
)

func file_components_transponder_codes_proto_rawDescGZIP() []byte {
	file_components_transponder_codes_proto_rawDescOnce.Do(func() {
		file_components_transponder_codes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_transponder_codes_proto_rawDesc), len(file_components_transponder_codes_proto_rawDesc)))
	})
	return file_components_transponder_codes_proto_rawDescData
}

var file_components_transponder_codes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_transponder_codes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_transponder_codes_proto_goTypes = []any{
	(InterrogationResponse)(0), // 0: components.InterrogationResponse
	(*Mode5)(nil),              // 1: components.Mode5
	(*ModeS)(nil),              // 2: components.ModeS
	(*TransponderCodes)(nil),   // 3: components.TransponderCodes
}
var file_components_transponder_codes_proto_depIdxs = []int32{
	0, // 0: components.Mode5.mode5_interrogation_response:type_name -> components.InterrogationResponse
	0, // 1: components.TransponderCodes.mode4_interrogation_response:type_name -> components.InterrogationResponse
	1, // 2: components.TransponderCodes.mode5:type_name -> components.Mode5
	2, // 3: components.TransponderCodes.modeS:type_name -> components.ModeS
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_components_transponder_codes_proto_init() }
func file_components_transponder_codes_proto_init() {
	if File_components_transponder_codes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_transponder_codes_proto_rawDesc), len(file_components_transponder_codes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_transponder_codes_proto_goTypes,
		DependencyIndexes: file_components_transponder_codes_proto_depIdxs,
		EnumInfos:         file_components_transponder_codes_proto_enumTypes,
		MessageInfos:      file_components_transponder_codes_proto_msgTypes,
	}.Build()
	File_components_transponder_codes_proto = out.File
	file_components_transponder_codes_proto_goTypes = nil
	file_components_transponder_codes_proto_depIdxs = nil
}
